<?php if ($this->getItems()->getSize()): ?>
    <?php foreach ($this->getItems() as $_rule): ?>
        <?php if ($_rule->getItems()->getSize()): ?>
            <?php if (count($_rule->getGiftCartItems($this->getQuote())) == 0): ?>
                <div class="giftselect">
                    <ul class="messages">
                        <li class="notice-msg">
                            <ul>
                                <li>
                                    <span><?php echo $this->__("You qualify for a gift, please <a href='%s'>view your cart</a> to select your gift", $this->getCartUrl()); ?></span>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <?php break;
            endif; ?> 
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>
