<?php ?>
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $this->__('Error 503: Service Unavailable') ?></title>
<style>
body {
    background: none repeat scroll 0 0 #D9D9D9;
    color: #FFFFFF;
    font-family: 'Lato';
    font-size: 13px;
    line-height: 19px;
    margin: 0;
    overflow-x: hidden;
    overflow-y: scroll;
}
#wrapper1 {
    background-size: cover;
    height: 100%;
    overflow: hidden;
}
#wrapper2 {
    height: 100%;
    left: 0;
    padding: 50px 0 310px;
    top: 0;
    width: 100%;
}
#wrapper2 .container {
    margin: auto;
    overflow: hidden;
    width: 100%;
}
#wrapper2 .container .logo {
    float: none;
    margin-right: 0;
    padding: 50px 50px 90px 0;
    width: 100%;
}

#wrapper2 .container .logo img {
    background: none repeat scroll 0 0 #FFFFFF;
    border: 2px solid #C8C8C8;
    border-radius: 6px;
    padding: 25px 55px;
}
#wrapper2 .container .logo img {
	background: #fff;
padding: 25px 55px;
border: 2px solid #c8c8c8;
border-radius: 6px;
}
#wrapper2 .container .icon {
	float: none;
	padding:0px 50px 30px 0px;
	margin-right:0px;
	width:100%;
}
#wrapper2 .container .description {
	float: left;
	width: 100%;
	text-align: left;
	font-size: 16px;
	padding: 0px 0px 50px;
}

#wrapper2 .container .description h2 {
	font-family: 'Lato';
	color: #333;
	font-size: 30px;
	padding-left: 0px;
	font-style: normal;
	letter-spacing: 1px;
	font-weight: bold;
	line-height: 1.2em;
	text-align:center;
	margin-bottom:15px;
	font-weight:400;
}
#wrapper2 .container .description P {
	text-align:center;
	width:600px;
	margin:auto;
	color:#333;
	font-size:24px;
	font-weight:100;
}
@media only screen and (min-width: 170px) and (max-width: 319px) {
#wrapper2 .container .description P {
	text-align:center;
	width:280px;
	margin:auto;
	color:#333;
	font-size:24px;
	font-weight:100;
}
}
@media only screen and (min-width: 320px) and (max-width: 479px) {
#wrapper2 .container .description P {
	text-align:center;
	width:300px;
	margin:auto;
	color:#333;
	font-size:24px;
	font-weight:100;
}
}
@media only screen and (min-width: 480px) and (max-width: 567px) {
#wrapper2 .container .description P {
	text-align:center;
	width:460px;
	margin:auto;
	color:#333;
	font-size:24px;
	font-weight:100;
}
}

</style>
<body>
<center>
    	<div id="wrapper1">
	    <div id="wrapper2">
        	<div class="container">
            	<div class="logo">
                	<img src="<?php echo $this->getSkinUrl('images/maintenancelogo.png');?>" alt="logoimage"/>
                </div>
            </div>
            <div class="container">
            	<div class="icon">
                	<img src="<?php echo $this->getSkinUrl('images/maintenance_icon1.png');?>" alt="maintenanceImage"/>
                </div>
                <div class="description">
                	<h2> Sorry! We're down for maintenance. </h2>
                	<p> We will be back shortly.</p>
                </div>
            </div>
            
	  </div>
        </div>
</center>
</body>
</html>