<?php if ($this->getItems()->getSize()): ?>
    <?php
    foreach ($this->getItems() as $giftItemKey => $_object):
        ?>
        <?php if ($this->canDisplay($_object, $giftItemKey) && $_object->getItems()->getSize()): ?>
            <?php
            $_giftItems = $this->filterItems($_object);
            ?>
            <?php if (count($_giftItems) > 0): ?>
                <div style="clear: both;">&nbsp;</div>
                <div class="giftselect">
                    <?php echo $this->getSelectGiftMessage($_object); ?>
                    <ul id="giftselect-products-list">
                        <?php foreach ($_giftItems as $itemKey => $_item): ?>
                            <?php $_item = $this->addUniqueId($_item); ?>
                            <form method="post" action="<?php echo $this->getAddToCartUrl($_item) ?>" id="giftpromo_select_form_<?php echo $_item->getGiftUid(); ?>_<?php echo $giftItemKey; ?>">
                                <input type="hidden" name="product" value="<?php echo $_item->getId(); ?>"/>
                                <input type="hidden" name="rule_id" value="<?php echo $_item->getGiftRuleId(); ?>"/>
                                <input type="hidden" name="selected_gift_item_key" value="<?php echo $giftItemKey; ?>"/>
                                <?php $giftParentItem = $_item->getGiftParentItem(); ?>
                                <?php if (is_object($giftParentItem)): ?>
                                    <input type="hidden" name="gift_parent_item_id" value="<?php echo $giftParentItem->getId(); ?>"/>
                                <?php endif; ?>
                                <li class="item">
                                    <a class="product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>"><img src="<?php echo $this->getProductThumbnail($_item)->resize(100); ?>" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" /></a>
                                    <h3 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></h3>
                                    <?php echo $this->getPriceHtml($_item, false) ?>
                                    <?php if ($_item->isSaleable()): ?>
                                        <?php if ($this->hasOptions($_item)): ?>
                                            <?php echo $this->getOptionsHtml($_item); ?>
                                        <?php endif; ?>
                                        <?php if (!$this->isCurrentSelected($_item, $giftItemKey)): ?>
                                            <?php $buttonText = (!$this->hasCurrentSelected($_item, $_object->getGiftParentItem(), $giftItemKey)) ? $this->__('Add to Cart') : $this->__('Replace Gift'); ?>
                                            <button type="button" title="<?php echo $buttonText ?>" class="button btn-cart" onclick="giftAddToCartForm<?php echo $_item->getGiftUid(); ?>_<?php echo $giftItemKey; ?>.submit();"><span><span><?php echo $buttonText ?></span></span></button>
                                        <?php else: ?>
                                            <div class="selected-gift"><?php echo $this->__('Selected Gift'); ?></div>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                            <?php endif; ?>
                                </li>
                            </form>
                            <script type="text/javascript">
                                //<![CDATA[
                                var giftAddToCartForm<?php echo $_item->getGiftUid(); ?>_<?php echo $giftItemKey; ?> = new VarienForm('giftpromo_select_form_<?php echo $_item->getGiftUid(); ?>_<?php echo $giftItemKey; ?>');
                                //]]>
                            </script>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>
