<script type="text/javascript">
    //<![CDATA[
    function updateautocomplete() {

        var email=$('autocompleteplus_config_store_email').value;

        if(email==undefined || email==''){

            email='no@email.com';
        }
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method:     'post',
            parameters: {email: email},
            onSuccess: function(transport){
 
              if (transport.responseText){
                  alert(transport.responseText);
                  configForm.submit();
              }
            }
        });
    }
    //]]>
</script>
 
<?php echo $this->getButtonHtml() ?>