<?php 
/* Top shopping Cart  */ 
?>
<div class="top-cart-contain">
  <div class="mini-cart">
  <div class="basket dropdown-toggle" data-hover="dropdown" data-toggle="dropdown"> 

     
      <a href="<?php echo $this->getUrl('checkout/cart') ?>"><i class="icon-cart"></i> <div class="cart-box"><span class="title"><?php echo $this->__('Cart');?></span><span id="cart-total"> <?php if(Mage::helper('checkout/cart')->getSummaryCount() > 1) { echo Mage::helper('checkout/cart')->getSummaryCount() . $this->__(' items'); } elseif(Mage::helper('checkout/cart')->getSummaryCount() == 1) { echo "1 item"; }  else {echo "0 item"; } ?> </span></div></a></div>
      <div>
      <div class="top-cart-content  arrow_box">
         <?php $_items = $this->getRecentItems() ?>

         <?php if(count($_items)): ?>   
           <div class="block-subtitle"><?php echo $this->__('Recently added item(s)') ?></div> 
            <ul id="cart-sidebar" class="mini-products-list">
               <?php foreach($_items as $_item): ?>
                   <?php echo $this->getItemHtml($_item) ?>
               <?php endforeach; ?>               
            </ul>                              
            <div class="top-subtotal">
                 <?php echo $this->__('Subtotal:');?>                   
                 <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>            
            </div> <!--top-subtotal-->
            <div class="actions">
              <button type="button" class="view-cart" onclick="window.location='<?php echo $this->getUrl('checkout/cart') ?>';" title="<?php echo $this->__('View Cart') ?>" ><span><?php echo $this->__('View Cart') ?></span></button>                 
              
	      <?php if(Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcgeneral_group/mgkextenable')==1){?>
		    <button type="button" title="<?php echo $this->__('Checkout') ?>" class="btn-checkout" onclick="window.location='<?php echo $this->getUrl('')?>onestepcheckout/';"><span><?php echo $this->__('Checkout') ?></span></button>                         
	      <?php }else{ ?>
		    <button type="button" title="<?php echo $this->__('Checkout') ?>" class="btn-checkout" onclick="window.location='<?php echo $this->getUrl('')?>checkout/onepage/';"><span><?php echo $this->__('Checkout') ?></span></button>                         
	      <?php }?>
              <!--<button type="button" title="<?php //echo $this->__('Checkout') ?>" class="btn-checkout" onclick="window.location='<?php //echo $this->getCheckoutUrl() ?>';"><span><?php //echo $this->__('Checkout') ?></span></button> -->                        

            </div>  <!--actions-->
           <?php else: ?>               
                <p class="a-center noitem"><?php echo $this->__('You have no items in your shopping cart.') ?></p>               
            <?php endif ?>
      </div> <!--top-cart-content-->
  </div>
  </div> <!--mini-cart-->
</div> <!--top-cart-contain-->