<?php
	$thumnailWidth = Mage::getStoreConfig('blog/info/recent_thumbnail_width');
    $thumnailHeight = Mage::getStoreConfig('blog/info/recent_thumbnail_height');
    $pageLayout = str_replace(array('page/','.phtml'),'',Mage::app()->getLayout()->getBlock('root')->getTemplate());
    $limit = 3;
    if (($pageLayout=="3columns")|| ($pageLayout=="2columns-right")){
    	$limit = 2;
    }
?>
<?php if(Mage::getStoreConfig('blog/menu/show_recent_post')):?>
<div class="block em_block-recent-post">
    <div class="block-title">
    	 
        <a href="<?php echo Mage::getBaseUrl().Mage::getStoreConfig('blog/info/url_key');?>"><strong><span><?php echo $this->__('From our Blog'); ?></span></strong></a>
        <p>Maecenas a sapien tortor quis tincidunt lectus. Donec ullamcorper dui sit amet sed porttito</p>
    </div>
    <div class="block-content">
        <ol>
            <?php $i=0; foreach ($this->getRecentPost() as $p): $i++; ?>
                <li class="item">
                	<?php if($p->getImage()):?>
						<a class="item-image" href="<?php echo $p->getPostUrl();?>">
							<img src="<?php echo Mage::helper('blog')->resizeImage($p->getImage(),$thumnailWidth,$thumnailHeight,"emblog/post",'thumbnail');?>"/>
							<span class = "bottom"></span>
						</a>
					<?php endif;?>
					<div class="item-content">
						<?php 
	                    	$title = $p->getTitle();
	                    	if(strlen($title) > 20 ){					
						    	$tam	=	substr($title, 0, 20);
						    	$plit	=	explode(" ", $tam);					
						    	$tam	=	array_slice($plit,0,count($plit)-1);
						    	$title	=	implode(" ", $tam).' [...]';
						     } 
	                    ?>
	                    <a class="post-title" href="<?php echo Mage::getUrl('blog').$p->getPostIdentifier().'.html';?>" ><?php echo $title?></a>
	                    <?php 
	                    	$intro = $p->getPostIntro();
	                    	if(strlen($intro) > 80 ){					
						    	$tam	=	substr($intro, 0, 80);
						    	$plit	=	explode(" ", $tam);					
						    	$tam	=	array_slice($plit,0,count($plit)-1);
						    	$intro	=	implode(" ", $tam).' [...]';
						     } 
	                    ?>
	                    <p><?php echo $intro ?> <a href="<?php echo $p->getPostUrl();?>"><span>Read more</span></a></p>
                    </div>
                </li>
            <?php if($i==3) break; endforeach; ?>
        </ol>
    </div>
</div>
<?php endif;?>