<?php
// @codingStandardsIgnoreFile

/**
 * @var Infortis\Base\Block\Html\Header\Logo $block
 */
?>
<?php
    $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();
?>
<?php if ($block->isHomePage()):?>
    <h1 class="logo">
        <a href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
            <strong><?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?></strong>
            <img src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>"
                 alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
                 <?php echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
                 <?php echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
            />
        </a>
    </h1>
<?php else: ?>
        <a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
            <strong><?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?></strong>
            <img src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>"
                 alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
                 <?php echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
                 <?php echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
            />
        </a>
<?php endif?>
