<div class="entry-edit-head">
	<h4 class="icon-head head-customer-address-list">
		<?php if( $this->isEdit() ): ?>
			<?php echo $this->__('Editing %s', $this->getCard()->getLabel() ); ?>
		<?php else: ?>
			<?php echo $this->__('Add A Bank Account (eCheck)') ?>
		<?php endif; ?>
	</h4>
</div>
<div class="fieldset">
	<input type="hidden" name="<?php echo $this->getCode(); ?>[card_id]" value="<?php echo $this->getCard()->getId(); ?>" />
	
	<h4><?php echo $this->__('Customer Information') ?></h4>
	<table class="form-list" cellspacing="0">
		<tr>
			<td class="label"><label for="<?php echo $this->getCode(); ?>_fn"><?php echo $this->__('First Name') ?> <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" id="<?php echo $this->getCode(); ?>_fn" name="<?php echo $this->getCode(); ?>[billing][firstname]" class="input-text" value="<?php echo $this->escapeHtml( $this->getCard()->getAddress('firstname') ); ?>" />
			</td>
		</tr>
		<tr>
			<td class="label"><label for="<?php echo $this->getCode(); ?>_ln"><?php echo $this->__('Last Name') ?> <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" id="<?php echo $this->getCode(); ?>_ln" name="<?php echo $this->getCode(); ?>[billing][lastname]" class="input-text" value="<?php echo $this->escapeHtml( $this->getCard()->getAddress('lastname') ); ?>" />
			</td>
		</tr>
		<tr>
			<td class="label"><label for="<?php echo $this->getCode(); ?>_company"><?php echo $this->__('Company') ?></label></td>
			<td class="value">
				<input type="text" id="<?php echo $this->getCode(); ?>_company" name="<?php echo $this->getCode(); ?>[billing][company]" class="input-text" value="<?php echo $this->escapeHtml( $this->getCard()->getAddress('company') ); ?>" />
			</td>
		</tr>
		<tr>
			<td class="label"><label for="<?php echo $this->getCode(); ?>_street"><?php echo $this->__('Street Address') ?> <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" id="<?php echo $this->getCode(); ?>_street" name="<?php echo $this->getCode(); ?>[billing][street][]" class="input-text" value="<?php echo $this->escapeHtml( $this->getCard()->getAddress('street') ); ?>" />
			</td>
		</tr>
		<tr>
			<td class="label"><label for="<?php echo $this->getCode(); ?>_city"><?php echo $this->__('City') ?> <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" id="<?php echo $this->getCode(); ?>_city" name="<?php echo $this->getCode(); ?>[billing][city]" class="input-text" value="<?php echo $this->escapeHtml( $this->getCard()->getAddress('city') ); ?>" />
			</td>
		</tr>
		<tr>
			<td class="label"><label for="<?php echo $this->getCode(); ?>_region_id"><?php echo $this->__('State/Province') ?> <span class="required">*</span></label></td>
			<td class="value">
				<select class="validate-select" title="State/Province" name="<?php echo $this->getCode(); ?>[billing][region_id]" id="<?php echo $this->getCode(); ?>_region_id">
					<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
				</select>
				<script type="text/javascript">
					$('<?php echo $this->getCode(); ?>_region_id').setAttribute('defaultValue', '<?php echo $this->getCard()->getAddress("region_id"); //Mage::getModel("directory/region")->loadByName( $this->getCard()->getAddress("region_code"), $this->getCard()->getAddress("country_id") )->getId(); ?>');
				</script>
				<input type="text" class="input-text" title="State/Province" value="<?php echo $this->escapeHtml( $this->getCard()->getAddress('region') ); ?>" name="<?php echo $this->getCode(); ?>[billing][region]" id="<?php echo $this->getCode(); ?>_region" />
			</td>
		</tr>
		<tr>
			<td class="label"><label for="<?php echo $this->getCode(); ?>_postcode"><?php echo $this->__('Zip/Postal Code') ?> <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" id="<?php echo $this->getCode(); ?>_postcode" name="<?php echo $this->getCode(); ?>[billing][postcode]" class="input-text" value="<?php echo $this->escapeHtml( $this->getCard()->getAddress('postcode') ); ?>" />
			</td>
		</tr>
		<tr>
			<td class="label"><label for="<?php echo $this->getCode(); ?>_country"><?php echo $this->__('Country') ?> <span class="required">*</span></label></td>
			<td class="value">
				<?php echo Mage::helper('tokenbase')->getCountryHtmlSelect( $this->getCode() . '[billing][country_id]', $this->getCard()->getAddress('country_id'), $this->getCode().'_country' ); ?>
			</td>
		</tr>
		<tr>
			<td class="label"><label for="<?php echo $this->getCode(); ?>_telephone"><?php echo $this->__('Telephone') ?> <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" id="<?php echo $this->getCode(); ?>_telephone" name="<?php echo $this->getCode(); ?>[billing][telephone]" class="input-text" value="<?php echo $this->escapeHtml( $this->getCard()->getAddress('telephone') ); ?>" />
			</td>
		</tr>
		<tr>
			<td class="label"><label for="<?php echo $this->getCode(); ?>_fax"><?php echo $this->__('Fax') ?></label></td>
			<td class="value">
				<input type="text" id="<?php echo $this->getCode(); ?>_fax" name="<?php echo $this->getCode(); ?>[billing][fax]" class="input-text" value="<?php echo $this->escapeHtml( $this->getCard()->getAddress('fax') ); ?>" />
			</td>
		</tr>
	</table>
		
	<h4><?php echo $this->__('Credit Card Information') ?></h4>
	<?php if( $this->isEdit() ): ?>
		<div>
			<input type="radio" name="<?php echo $this->getCode(); ?>[payment][sameCard]" value="1" id="<?php echo $this->getCode(); ?>_sameCard_1" checked="checked" /> <label for="<?php echo $this->getCode(); ?>_sameCard_1"><?php echo $this->__( 'Continue using payment data %s', $this->getCard()->getLabel() ); ?></label><br />
			<input type="radio" name="<?php echo $this->getCode(); ?>[payment][sameCard]" value="0" id="<?php echo $this->getCode(); ?>_sameCard_0" /> <label for="<?php echo $this->getCode(); ?>_sameCard_0"><?php echo $this->__('Change payment data'); ?></label>
		</div>
	<?php endif; ?>
	<table class="form-list" cellspacing="0" <?php if( $this->isEdit() ): ?>style="display:none"<?php endif; ?> id="<?php echo $this->getCode(); ?>_ccInfo">
		<tr>
			<td class="label"><label for="<?php echo $this->getCode(); ?>_echeck_account_name"><?php echo $this->__('Name on Account') ?> <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" id="<?php echo $this->getCode(); ?>_echeck_account_name" name="<?php echo $this->getCode(); ?>[payment][echeck_account_name]" title="<?php echo $this->__('Name on Account') ?>" class="input-text" value="<?php echo $this->escapeHtml( $this->getCard()->getAdditional('echeck_account_name') ); ?>" maxlength="22" />
			</td>
		</tr>
		<tr>
			<td class="label"><label for="<?php echo $this->getCode(); ?>_echeck_bank_name"><?php echo $this->__('Bank Name') ?> <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" id="<?php echo $this->getCode(); ?>_echeck_bank_name" name="<?php echo $this->getCode(); ?>[payment][echeck_bank_name]" title="<?php echo $this->__('Bank Name') ?>" class="input-text" value="<?php echo $this->escapeHtml( $this->getCard()->getAdditional('echeck_bank_name') ); ?>" maxlength="50" autocomplete="off" />
			</td>
		</tr>
		<tr>
			<td class="label"><label for="<?php echo $this->getCode(); ?>_echeck_routing_number"><?php echo $this->__('Routing Number') ?> <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" id="<?php echo $this->getCode(); ?>_echeck_routing_no" name="<?php echo $this->getCode(); ?>[payment][echeck_routing_no]" title="<?php echo $this->__('Routing Number') ?>" class="input-text <?php if( !$this->isEdit() ): ?>validate-number<?php endif; ?>" value="<?php if( $this->getCard()->getId() ): ?>XXXX<?php echo $this->getCard()->getAdditional('echeck_routing_number_last4'); ?><?php endif; ?>" maxlength="9" autocomplete="off" />
			</td>
		</tr>
		<tr>
			<td class="label"><label for="<?php echo $this->getCode(); ?>_echeck_account_number"><?php echo $this->__('Account Number') ?> <span class="required">*</span></label></td>
			<td class="value">
				<input type="text" id="<?php echo $this->getCode(); ?>_echeck_account_no" name="<?php echo $this->getCode(); ?>[payment][echeck_account_no]" title="<?php echo $this->__('Account Number') ?>" class="input-text <?php if( !$this->isEdit() ): ?>validate-number<?php endif; ?>" value="<?php if( $this->getCard()->getId() ): ?>XXXX<?php echo $this->getCard()->getAdditional('echeck_account_number_last4'); ?><?php endif; ?>" maxlength="17" autocomplete="off" />
			</td>
		</tr>
		<tr>
			<td class="label"><label for="<?php echo $this->getCode(); ?>_echeck_account_type"><?php echo $this->__('Account Type') ?> <span class="required">*</span></label></td>
			<td class="value">
				<select id="<?php echo $this->getCode(); ?>_echeck_account_type" name="<?php echo $this->getCode(); ?>[payment][echeck_account_type]">
					<?php foreach( Mage::helper('authnetcim_ach')->getAchAccountTypes() as $k => $v ): ?>
						<option value="<?php echo $k; ?>" <?php if( $k == $this->getCard()->getAdditional('echeck_account_type') ): ?>selected="selected"<?php endif ?>><?php echo $v; ?></option>
					<?php endforeach ?>
				</select>
			</div>
		</li>
	</table>
	
	<table class="form-list" cellspacing="0">
		<tr>
			<td class="label"></td>
			<td class="value">
				<button class="button" type="button" onclick="<?php echo $this->getCode(); ?>.saveCard();"><span><?php echo $this->__('Save') ?></span></button>
				<a href="#" onclick="<?php echo $this->getCode(); ?>.editCard(0); return false;"><?php echo $this->__('Cancel'); ?></a>
			</td>
		</tr>
	</table>
</div>
<script type="text/javascript">
//<![CDATA[
	new RegionUpdater('<?php echo $this->getCode(); ?>_country', '<?php echo $this->getCode(); ?>_region', '<?php echo $this->getCode(); ?>_region_id', <?php echo Mage::helper('directory')->getRegionJson() ?>, undefined, '<?php echo $this->getCode(); ?>_postcode');
	
	$$('#<?php echo $this->getCode(); ?>_sameCard_0, #<?php echo $this->getCode(); ?>_sameCard_1').each(function(el) {
		$(el).observe( 'change', function(e) {
			$('<?php echo $this->getCode(); ?>_ccInfo').toggle();
		});
	});
	
	function <?php echo $this->getCode(); ?>_clearAddrValidation() {
		$('<?php echo $this->getCode(); ?>_region_id').removeClassName('required-entry').removeClassName('validate-select');
		$('<?php echo $this->getCode(); ?>_country').removeClassName('required-entry').removeClassName('validate-select');
		$('<?php echo $this->getCode(); ?>_region').removeClassName('required-entry');
	}
	
	/* Prevent the region from holding up submit... unfortunately no better way to do this. */
	document.observe("dom:loaded", function() {
		<?php echo $this->getCode(); ?>_clearAddrValidation();
		
		setInterval( function() {
			<?php echo $this->getCode(); ?>_clearAddrValidation();
		}, 10000 );
	});
//]]>
</script>
