<?php

/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
$catalogSearchHelper =  $this->helper('catalogsearch');
?>

 <div class="search-box">
   <form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">       
	<?php 
	      $enabled=Mage::app()->getStore()->getConfig('mgkautocompletesection/general/enabled');
	      $loderimage=Mage::app()->getStore()->getConfig('mgkautocompletesection/general/loaderimg');
	      if($enabled==1){
		  if($loderimage==''){  
			  $selectedlodader=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'magikautocomplete/default/autocomplete_loader.gif';        
		  }else{ 
			  $selectedlodader = Mage::getBaseUrl('media').'magikautocomplete'.DS.$loderimage;       
		  }
	?>
	      <div style="display:none;" class="magikautosearchImg" id="processing-image">
		<img src="<?php echo $selectedlodader;?>">
	      </div>	
	<?php } ?>
	<!-- Autocomplete End code -->
        <input id="search" type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>" class="searchbox" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" />
        <button type="submit" title="<?php echo $this->__('Search') ?>" class="search-btn-bg" id="submit-button"><span><?php echo $this->__('Search') ?></span></button>
        <div id="search_autocomplete" class="search-autocomplete"></div>
        <script type="text/javascript">
	    var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search entire store here...') ?>');
jQuery('html').click(function(){
jQuery('#search_autocomplete').hide();
});
	    jQuery("#search").keyup(function() {
		var text = jQuery(this).val();
		var chars = text.length;
		if (chars > 2) {
		    jQuery("#processing-image").show();
		    var postData = jQuery('#search_mini_form').serializeArray();
    
		    jQuery.ajax({
			      url : '<?php echo $catalogSearchHelper->getSuggestUrl() ?>',
			      type: "POST",
			      data : postData,
			      success:function(data)
			      { jQuery("#processing-image").hide();
				    jQuery('#search_autocomplete').html(data).show();
				}
		    });
		}
    
	    });
	</script>    
   </form>
 </div> <!--search-box-->