<?php
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Currency switcher
 *
 * @see \Magento\Directory\Block\Currency
 */
?>
<?php if ($block->getCurrencyCount() > 1): ?>
<?php $currencies = $block->getCurrencies(); ?>
<?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<div class="dropdown-block currency-switcher<?php if ($id) echo ' currency-switcher' . $id; ?>" id="switcher-currency<?php /* @escapeNotVerified */ echo $id?>">
    <div class="dropdown-heading cover">
        <span class="language-<?php echo $block->escapeHtml($block->getCurrentCurrencyCode()) ?>">
            <span class="label"><?php /* @escapeNotVerified */ echo __('Currency') ?></span>
            <span class="value"><?php echo $block->escapeHtml($currentCurrencyCode) ?></span>
            <span class="caret"></span>
        </span>
    </div>
    <ul class="dropdown-content left-hand">
        <?php foreach ($currencies as $_code => $_name): ?>
            <?php if ($_code != $currentCurrencyCode): ?>
                <li class="currency-<?php /* @escapeNotVerified */ echo $_code ?> switcher-option">
                    <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getSwitchCurrencyPostData($_code); ?>'><?php /* @escapeNotVerified */ echo $_code ?> - <?php /* @escapeNotVerified */ echo $_name ?></a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
