<?php if($this->getItems()->getSize()): ?>
<?php foreach ($this->getItems() as $_rule): ?>
<?php if($_rule->getItems()->getSize()): ?>

<div style="clear: both;">&nbsp;</div>
<div class="giftselect">
    <h2><?php echo $this->__("You qualify for a gift from rule '%s', please select <b>one</b> of the following items:", $_rule->getRuleName()) ?></h2>
    <ul id="giftselect-products-list">
    <?php foreach ($_rule->getItems() as $_item): ?>
        <li class="item">
            <a class="product-image" href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(75); ?>" width="75" height="75" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
            <div class="product-details">
                <h3 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></h3>
                <?php echo $this->getPriceHtml($_item, true) ?>
                <br/>
                <?php if(!$this->isCurrentSelected($_item)):?>
                    <?php $buttonText = (!$this->hasCurrentSelected($_item))?$this->__('Add to Order'):$this->__('Replace'); ?>
                    <button type="button" title="<?php echo $buttonText ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"><span><span><?php echo $buttonText ?></span></span></button>
                <?php else: ?>
                    <div class="selected-gift"><?php echo $this->__('Selected Gift'); ?></div>
                <?php endif; ?>
            </div>
        </li>
    <?php endforeach; ?>
    </ul>
    <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>
</div>
<?php endif; ?>
<?php endforeach; ?>
<?php endif; ?>
