<?php $requireClass	= ( $this->haveStoredCards() ? $this->getMethodCode() . '_require' : 'required-entry' ); ?>
<?php $newClass		= $this->getMethodCode() . '_new'; ?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display:none;">
	<?php if( $this->getMethod()->getConfigData('show_branding') ): ?>
		<li class="right pages">
			<img src="<?php echo $this->getSkinUrl( 'images/' . $this->getMethodCode() . '/logo.png' ); ?>" />
		</li>
	<?php endif; ?>
	<?php if( $this->haveStoredCards() ): ?>
		<li>
			<label for="<?php echo $this->getMethodCode(); ?>_payment_id"><?php echo $this->__('Pay with account on file'); ?></label>
			<div class="input-box">
				<select name="payment[card_id]" id="<?php echo $this->getMethodCode(); ?>_card_id" class="<?php echo $this->getMethodCode(); ?>_require required-entry">
					<option value=""><?php echo $this->__('-- Select One --'); ?></option>
					<?php foreach( $this->getStoredCards() as $card ): ?>
						<?php $card = $card->getTypeInstance(); ?>
						<option value="<?php echo $card->getHash(); ?>" <?php if( $card->getId() == $this->getInfoData('tokenbase_id') || count( $this->getStoredCards() ) == 1 ): ?>selected="selected"<?php endif; ?>><?php echo $card->getLabel(); ?></option>
					<?php endforeach; ?>
				</select>
			</div>
		</li>
		<li>
			<div class="input-box">
				<?php echo $this->__('Or,'); ?> <a href="#" id="<?php echo $this->getMethodCode(); ?>_add_new"><?php echo $this->__('use a different account.'); ?></a>
			</div>
		</li>
	<?php endif; ?>
	<li <?php if( $this->haveStoredCards() ): ?>style="display:none"<?php endif; ?> class="<?php echo $newClass; ?>">
		<label for="<?php echo $this->getMethodCode(); ?>_echeck_account_name" class="required"><em>*</em><?php echo $this->__('Name on Account') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $this->getMethodCode(); ?>_echeck_account_name" name="payment[echeck_account_name]" title="<?php echo $this->__('Name on Account') ?>" class="input-text <?php echo $requireClass; ?>" value="<?php echo $this->escapeHtml( $this->getInfoData('echeck_account_name') ); ?>" maxlength="22" />
		</div>
	</li>
	<li <?php if( $this->haveStoredCards() ): ?>style="display:none"<?php endif; ?> class="<?php echo $newClass; ?>">
		<label for="<?php echo $this->getMethodCode(); ?>_echeck_bank_name" class="required"><em>*</em><?php echo $this->__('Bank Name') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $this->getMethodCode(); ?>_echeck_bank_name" name="payment[echeck_bank_name]" title="<?php echo $this->__('Bank Name') ?>" class="input-text <?php echo $requireClass; ?>" value="<?php echo $this->escapeHtml( $this->getInfoData('echeck_bank_name') ); ?>" maxlength="50" autocomplete="off" />
		</div>
	</li>
	<li <?php if( $this->haveStoredCards() ): ?>style="display:none"<?php endif; ?> class="<?php echo $newClass; ?>">
		<label for="<?php echo $this->getMethodCode(); ?>_echeck_routing_number" class="required"><em>*</em><?php echo $this->__('Routing Number') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $this->getMethodCode(); ?>_echeck_routing_no" name="payment[echeck_routing_no]" title="<?php echo $this->__('Routing Number') ?>" class="input-text validate-number <?php echo $requireClass; ?>" value="<?php echo $this->escapeHtml( $this->getInfoData('echeck_routing_no') ); ?>" maxlength="9" autocomplete="off" />
		</div>
	</li>
	<li <?php if( $this->haveStoredCards() ): ?>style="display:none"<?php endif; ?> class="<?php echo $newClass; ?>">
		<label for="<?php echo $this->getMethodCode(); ?>_echeck_account_number" class="required"><em>*</em><?php echo $this->__('Account Number') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $this->getMethodCode(); ?>_echeck_account_no" name="payment[echeck_account_no]" title="<?php echo $this->__('Account Number') ?>" class="input-text validate-number <?php echo $requireClass; ?>" value="<?php echo $this->escapeHtml( $this->getInfoData('echeck_account_no') ); ?>" maxlength="17" autocomplete="off" />
		</div>
	</li>
	<li <?php if( $this->haveStoredCards() ): ?>style="display:none"<?php endif; ?> class="<?php echo $newClass; ?>">
		<small><a href="#" id="<?php echo $this->getMethodCode(); ?>_check_expln"><?php echo $this->__('Where do I find these numbers?'); ?></a></small>
		<div id="<?php echo $this->getMethodCode(); ?>_check_expln_contents" style="display:none">
			<p><?php echo $this->__('On the bottom of your checks, you will see three groups of numbers. Usually the first one is your routing number, and the second is your account number.'); ?></p>
			<img src="<?php echo $this->getSkinUrl( 'images/' . $this->getMethodCode() . '/checkNumbers.png' ); ?>" alt="Visual reference for locating routing number and account number on a check" />
		</div>
	</li>
	<li <?php if( $this->haveStoredCards() ): ?>style="display:none"<?php endif; ?> class="<?php echo $newClass; ?>">
		<label for="<?php echo $this->getMethodCode(); ?>_echeck_account_type" class="required"><em>*</em><?php echo $this->__('Account Type') ?></label>
		<?php $typeValue = ( $this->getInfoData('echeck_account_type') != '' ) ? $this->getInfoData('echeck_account_type') : 'checking'; ?>
		<?php foreach( Mage::helper('authnetcim_ach')->getAchAccountTypes() as $k => $v ): ?>
			<div class="input-box">
				<input type="radio" name="payment[echeck_account_type]" id="<?php echo $this->getMethodCode(); ?>_echeck_account_type_<?php echo $k; ?>" value="<?php echo $k; ?>" <?php if( $k == $typeValue ): ?>checked="checked"<?php endif ?> class="validate-one-required-by-name left" />
				<label for="<?php echo $this->getMethodCode(); ?>_echeck_account_type_<?php echo $k; ?>"><?php echo $v; ?></label>
			</div>
		<?php endforeach ?>
	</li>
	<?php echo $this->getChildHtml(); ?>
	<?php if( !$this->isNominalCheckout() && !$this->isGuestCheckout() && $this->getMethod()->getConfigData('allow_unsaved') ): ?>
		<li <?php if( $this->haveStoredCards() ): ?>style="display:none"<?php endif; ?> class="<?php echo $newClass; ?>">
			<label>&nbsp;</label>
			<input type="hidden" name="payment[save]" value="0" />
			<input type="checkbox" name="payment[save]" id="<?php echo $this->getMethodCode(); ?>_save" value="1" <?php if( $this->getMethod()->getConfigData('savecard_opt_out') ): ?>checked="checked" <?php endif; ?>autocomplete="on" /> 
			<label for="<?php echo $this->getMethodCode(); ?>_save" style="float:none;font-weight:normal;"><?php echo $this->__('Save for next time'); ?></label>
		</li>
	<?php elseif( $this->isNominalCheckout() || !$this->isGuestCheckout() ): ?>
		<li <?php if( $this->haveStoredCards() ): ?>style="display:none"<?php endif; ?> class="<?php echo $newClass; ?>">
			<?php echo $this->__('<strong>Note:</strong> For your convenience, this data will be stored securely by our payment processor.'); ?>
		</li>
	<?php else: /* Guests are not given any choice or warning, because the card can never be reused. */ ?>
	<?php endif; ?>
</ul>
<script type="text/javascript">
//<![CDATA[
	<?php if( $this->haveStoredCards() ): ?>
		$('<?php echo $this->getMethodCode(); ?>_add_new').observe( 'click', function(e) {
			e.preventDefault();
			
			$$('.<?php echo $newClass; ?>').each(function(el) {
				el.toggle();
			});
			
			$$('.<?php echo $this->getMethodCode(); ?>_require').each(function(el) {
				el.toggleClassName('required-entry');
			});
			
			$('<?php echo $this->getMethodCode(); ?>_card_id').setValue(0);
			
			return false;
		});
		
		$('<?php echo $this->getMethodCode(); ?>_card_id').observe( 'change', function(e) {
			$$('.<?php echo $newClass; ?>').each(function(el) {
				el.hide();
			});
			
			$$('.<?php echo $newClass; ?> .<?php echo $this->getMethodCode(); ?>_require').each(function(el) {
				el.removeClassName('required-entry');
			});
			
			$$('#<?php echo $this->getMethodCode(); ?>_saved_cc_cid, #<?php echo $this->getMethodCode(); ?>_card_id').each(function(el) {
				el.addClassName('required-entry');
			});
			
			return false;
		});
	<?php endif; ?>
	
	$('<?php echo $this->getMethodCode(); ?>_check_expln').observe( 'click', function(e) {
		e.preventDefault();
		
		$('<?php echo $this->getMethodCode(); ?>_check_expln_contents').toggle();
		
		return false;
	});
//]]>
</script>
