<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()){ ?>
<div id="mgkosc-password">
      <a href="#" id="mgkoschidepassword" class="mgkosc-loginclose"><img src="<?php echo $this->getSkinUrl('mgkoscheckout/images/onestepcheckout/c-icon.png') ?>"  alt=""/></a>
     
      <div class="mgkosc-logincontent">
             <p class="mgkosc-logininfo"><?php echo $this->__('Forgot Password') ?></p>
	     <?php
		  $forgot_url	= $this->getUrl('*/*/forgotpassword', array('_secure'=>(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on')));
		  $http_mode	= (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on');
		  if($http_mode)
			  $forgot_url	= str_replace('http:', 'https:', $forgot_url);  
	      ?>

	      <form action="<?php echo $forgot_url ?>" method="post" id="forgot-password-form">
		  <div class="mgkosc-login-field">
		      <p class="mgkoscforgotpass"><?php echo $this->__('Please enter your email address below.<br/>You will receive a link to reset your password.') ?></p>
			<div class='mgkosc-login-text'>
				<label><?php echo $this->__('Email') ?><em> * </em></label>
				<div class="mgkosc-login-input-box">
					<input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
				</div>
			</div>
			
			    <button type="submit" title="<?php echo $this->__('Submit') ?>" id="btn-forgot" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
			    <span class="mgkosc-please-wait" id="forgot-please-wait" style="display:none;">
				<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt=""/>
			    </span>
			    <a href="javascript:void(0);" class="" id="mgkoscloginback"><?php echo $this->__('Back to Login') ?></a>
		    </div>
		</form>
	      <script type="text/javascript">
	      //<![CDATA[
		  var forgotForm = new VarienForm('forgot-password-form', true);
	      //]]>
	      </script>
      </div>
</div>
<?php }?>