<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()){?>
<div id="mgkosc-login">
      <a href="#" id="mgkoschidelogin" class="mgkosc-loginclose"><img src="<?php echo $this->getSkinUrl('mgkoscheckout/images/onestepcheckout/c-icon.png') ?>"  alt="" /></a>
      <div class="mgkosc-logincontent">
             <p class="mgkosc-logininfo"><?php echo $this->__('If you have an account with us,please log in.') ?></p>
	      <?php
		  $login_url = $this->getUrl('*/*/login', array('_secure'=>(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on')));
		  $http_mode = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on');
		  if($http_mode)
			  $login_url	= str_replace('http:', 'https:', $login_url);  
	    ?>  
	     <form method="post" id="login-form" action="<?php echo $login_url ?>">
		  <div class="mgkosc-login-field">
			<div class="mgkosc-login-text">
				<label><?php echo $this->__('Email Address') ?><em> * </em></label>
				<div class="mgkosc-login-input-box">
					<input type="text" name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
				</div>
			</div>
			<div class="mgkosc-login-text">
				<label><?php echo $this->__('Password') ?><em> * </em></label>
				<div class="mgkosc-login-input-box">
					<input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
				</div>
			</div>
			<button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
			<span class="mgkosc-please-wait" id="login-please-wait" style="display:none;">
			      <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt=""/>
			</span>
			<a href="javascript:void(0);" class="" id="mgkoscforgotpass"><?php echo $this->__('Forgot Your Password?') ?></a>
		  </div>
		  
		</form>
		<script type="text/javascript">
		//<![CDATA[
		    var loginForm = new VarienForm('login-form', true);
		//]]>
		</script>
 
      </div>
	  
</div>
<div id="mgkoscloginoverlay"></div>
<?php }?>