<?php
/**
* Copyright 2016 aheadWorks. All rights reserved.
* See LICENSE.txt for license details.
*/

/* @var $block \Magento\Framework\View\Element\Template */
?>
<script type="text/x-magento-init">
    {
        ".column.main": {
            "checkoutCartUpdate": {
                "partName": "<?php /* @noEscape */ echo \Aheadworks\Ajaxcartpro\Model\Renderer::PART_CHECKOUT_CART ?>"
            }
        }
    }
</script>
