<?php $footer_type = Mage::getStoreConfig('eclipsesettings/eclipsesettings_appearance/footer'); ?>



<footer>

<!-- Logo Brand Block -->
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('eclipse_logo_brand_block')->toHtml() ?>

<div class="footer <?php echo $footer_type;?>">

<!-- BEGIN INFORMATIVE FOOTER -->  
  <?php switch ($footer_type) {
      case 'informative' :
          ?>

<div class="newsletter-wrap">
  <div class="inner">
     <?php if (Mage::getStoreConfig('eclipsesettings/eclipsesettings_social/social_link')) { ?>
    <div class="social">      
       <ul class="link">
        <?php if (Mage::getStoreConfig('eclipsesettings/eclipsesettings_social/facebook_social_link')) { ?>
          <li class="fb"><a target="_blank" rel="nofollow" href="<?php echo Mage::getStoreConfig('eclipsesettings/eclipsesettings_social/facebook_social_link_path') ?>" title="<?php echo $this->__('Facebook');?>"></a></li>
        <?php } 
              if (Mage::getStoreConfig('eclipsesettings/eclipsesettings_social/twitter_social_link')) {
        ?>
          <li class="tw"><a target="_blank" rel="nofollow"  href="<?php echo Mage::getStoreConfig('eclipsesettings/eclipsesettings_social/twitter_social_link_path') ?>" title="<?php echo $this->__('Twitter');?>"></a></li>
        <?php } 
              if (Mage::getStoreConfig('eclipsesettings/eclipsesettings_social/googleplus_social_link')) {
        ?>
          <li class="googleplus"><a target="_blank" rel="nofollow" href="<?php echo Mage::getStoreConfig('eclipsesettings/eclipsesettings_social/googleplus_social_link_path') ?>" title="<?php echo $this->__('GooglePlus');?>"></a></li>
        <?php } 
              if (Mage::getStoreConfig('eclipsesettings/eclipsesettings_social/rss_social_link')) {
        ?>
          <li class="rss"><a target="_blank" rel="nofollow" href="<?php echo Mage::getStoreConfig('eclipsesettings/eclipsesettings_social/rss_social_link_path') ?>" title="<?php echo $this->__('RSS');?>"></a></li>
        <?php } 
              if (Mage::getStoreConfig('eclipsesettings/eclipsesettings_social/pinterest_social_link')) {
        ?>
          <li class="pintrest"><a target="_blank" rel="nofollow" href="<?php echo Mage::getStoreConfig('eclipsesettings/eclipsesettings_social/pinterest_social_link_path') ?>" title="<?php echo $this->__('PInterest');?>"></a></li>
        <?php } 
              if (Mage::getStoreConfig('eclipsesettings/eclipsesettings_social/linkedin_social_link')) {
        ?>
          <li class="linkedin"><a  target="_blank" rel="nofollow" href="<?php echo Mage::getStoreConfig('eclipsesettings/eclipsesettings_social/linkedin_social_link_path') ?>" title="<?php echo $this->__('Linkedin');?>"></a></li>
        <?php } 
              if (Mage::getStoreConfig('eclipsesettings/eclipsesettings_social/youtube_social_link')) {
        ?>
          <li class="youtube"><a target="_blank" rel="nofollow" href="<?php echo Mage::getStoreConfig('eclipsesettings/eclipsesettings_social/youtube_social_link_path') ?>" title="<?php echo $this->__('Youtube');?>"></a></li>
        <?php } ?>
       </ul>
    </div> <!--social-->
    <?php } ?>
    <!-- Footer Newsletter -->
    <?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe_footer.phtml')->toHtml() ; ?>
  </div> <!--inner-->
</div> <!--newsletter-wrap-->

<div class="inner">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('eclipse_footer_about_us')->toHtml() ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('eclipse_footer_information_links_block')->toHtml() ?>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('eclipse_footer_contact_us')->toHtml() ?>
</div> <!--inner-->
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('eclipse_footer_links')->toHtml() ?>
<script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script>

<!-- BEGIN SIMPLE FOOTER -->  
          <?php
          break;
      case 'simple' :
      default: ?>
     
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('eclipse_footer_links')->toHtml() ?>

     <?php     
  }
  ?> 

</div> <!--footer-->

</footer>

<?php if (Mage::getStoreConfig('eclipsesettings/eclipsesettings_footer/footer_google_analytics')): ?>
<?php echo Mage::getStoreConfig('eclipsesettings/eclipsesettings_footer/footer_google_analytics_path') ?>       
<?php endif; ?>
<div class="ajaxcartanimate"></div>