<?php $profile	= $this->getProfile(); ?>
<?php $itemInfo	= $profile->getOrderItemInfo(); ?>
<?php $product	= Mage::getModel('catalog/product')->load( $itemInfo['product_id'] ); ?>
<?php if( $product && $product->getId() == $itemInfo['product_id'] && $product->getData('allow_autoship') == 1 ): ?>
	<tr>
		<td class="label"><label for="subscription_period"><?php echo $this->__('Subscription Frequency') ?></label></td>
		<td class="value">
			<select name="subscription_period" id="subscription_period">
				<?php foreach( Mage::app()->getLayout()->createBlock('autoship/product_option')->getOptions() as $k => $v ): ?>
					<?php if( $k < 1 ) continue; ?>
					<option value="<?php echo $k; ?>" <?php if( $k == $this->getProfile()->getPeriodFrequency() ): ?>selected="selected"<?php endif; ?>><?php echo $v; ?></option>
				<?php endforeach; ?>
			</select>
		</td>
	</tr>
<?php endif; ?>
