<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Marketsuite
 * @version    2.1.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $useMssBackUrlFlag = $this->getRequest()->getParam(AW_Marketsuite_Helper_Data::USE_AW_BACKURL_FLAG); ?>
<?php
if ($useMssBackUrlFlag && ($backUrl = Mage::helper('marketsuite')->getBackUrl())) : ?>
    <script type="text/javascript">
        $$('button.back').each(function (el) {
            if ((typeof el == 'object') && el.hasAttribute('onclick')) {
                el.setAttribute('onclick', "setLocation('<?php echo $backUrl ?>')")
            }
        });
    </script>
<?php endif;
