<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Rules
 */
?>
<div class="amrules_notifications" id="amrules_notifications">
    <div id="messages">
        <ul class="messages">
            <li class="notice-msg">
                <ul>
                    <li>
                        <?php echo $this->__("In order to use attributes like SKU or Manufacturer, please activate `Use for Promo Rule Condition` option in ");?>
                        (<a href="<?php echo $this->getSettingsUrl();?>"><?php echo $this->__('Product Attributes');?></a>).
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>