<div class="<?php echo $this->getContainerClassName()?>">
<?php if ($this->showPrefix()): ?>
    <div class="mgkosc-field">
        <label for="<?php echo $this->getFieldId('prefix')?>">
        	<?php echo $this->__('Prefix'); ?><?php if ($this->isPrefixRequired()) echo ' <em class="required">*</em>'; ?>
        </label>
        
        <div class="mgkosc-box">
            <?php if ($this->getPrefixOptions()===false): ?>
                <input type="text" id="<?php echo $this->getFieldId('prefix')?>" name="<?php echo $this->getFieldName('prefix')?>" value="<?php echo $this->htmlEscape($this->getObject()->getPrefix()) ?>" title="<?php echo $this->__('Prefix') ?>" class="<?php if ($this->isPrefixRequired()):?>mgkosc-input-text required-entry<?php endif; ?>" <?php echo $this->getFieldParams() ?> />
            <?php else: ?>
                <select id="<?php echo $this->getFieldId('prefix')?>" name="<?php echo $this->getFieldName('prefix')?>" title="<?php echo $this->__('Prefix') ?>"<?php if ($this->isPrefixRequired()):?> class="required-entry"<?php endif; ?> <?php echo $this->getFieldParams() ?>>
                <?php foreach ($this->getPrefixOptions() as $_option): ?>
                    <option value="<?php echo $_option?>"<?php if ($this->getObject()->getPrefix()==$_option):?> selected="selected"<?php endif; ?>><?php echo $this->__($_option)?></option>
                <?php endforeach ?>
                </select>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
    <div class="mgkosc-field">
        <label for="<?php echo $this->getFieldId('firstname')?>">
        	<?php echo $this->__('First Name') ?><em class="required"> * </em>
        </label>
        <div class="mgkosc-box">
            <input type="text" id="<?php echo $this->getFieldId('firstname')?>" name="<?php echo $this->getFieldName('firstname')?>" value="<?php echo $this->htmlEscape($this->getObject()->getFirstname()) ?>" title="<?php echo $this->__('First Name') ?>" class="mgkosc-input-text required-entry" <?php echo $this->getFieldParams() ?> />
        </div>
    </div>
    <?php if ($this->showMiddlename()): ?>
    <div class="mgkosc-field">
        <label for="<?php echo $this->getFieldId('middlename')?>"><?php echo $this->__('M.I.') ?></label>
        <div class="mgkosc-box">
            <input type="text" id="<?php echo $this->getFieldId('middlename')?>" name="<?php echo $this->getFieldName('middlename')?>" value="<?php echo $this->htmlEscape($this->getObject()->getMiddlename()) ?>" title="<?php echo $this->__('M.I.') ?>" class="mgkosc-input-text" <?php echo $this->getFieldParams() ?> />
        </div>
    </div>
    <?php endif; ?>
    <div class="mgkosc-field">
        <label for="<?php echo $this->getFieldId('lastname')?>">
        	<?php echo $this->__('Last Name') ?><em class="required"> * </em>
        </label>
        <div class="mgkosc-box">
            <input type="text" id="<?php echo $this->getFieldId('lastname')?>" name="<?php echo $this->getFieldName('lastname')?>" value="<?php echo $this->htmlEscape($this->getObject()->getLastname()) ?>" title="<?php echo $this->__('Last Name') ?>" class="mgkosc-input-text required-entry" <?php echo $this->getFieldParams() ?> />
        </div>
    </div>
<?php if ($this->showSuffix()): ?>
    <div class="mgkosc-field">
        <label for="<?php echo $this->getFieldId('suffix')?>">
        	<?php echo $this->__('Suffix') ?>  <?php if ($this->isSuffixRequired()) echo '<em class="required">*</em>'; ?>
        </label>
       
        <div class="mgkosc-box">
        <?php if ($this->getSuffixOptions()===false): ?>
            <input type="text" id="<?php echo $this->getFieldId('suffix')?>" name="<?php echo $this->getFieldName('suffix')?>" value="<?php echo $this->htmlEscape($this->getObject()->getSuffix()) ?>" title="<?php echo $this->__('Suffix') ?>" class="mgkosc-input-text <?php if ($this->isSuffixRequired()):?> required-entry<?php endif; ?>" <?php echo $this->getFieldParams() ?> />
        <?php else: ?>
            <select id="<?php echo $this->getFieldId('suffix')?>" name="<?php echo $this->getFieldName('suffix')?>" title="<?php echo $this->__('Suffix') ?>"<?php if ($this->isSuffixRequired()):?> class="required-entry"<?php endif; ?> <?php echo $this->getFieldParams() ?>>
            <?php foreach ($this->getSuffixOptions() as $_option): ?>
                <option value="<?php echo $_option?>"<?php if ($this->getObject()->getSuffix()==$_option):?> selected="selected"<?php endif; ?>><?php echo $this->__($_option)?></option>
            <?php endforeach ?>
            </select>
        <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
</div>
