<?php if( Mage::registry('current_product')->getData('allow_autoship') ): ?>
	<?php $opts = $this->getOptions( true, true ); ?>
	<div id="subscription_period">
		<select name="subscription_period" id="subscription_period_select">
			<?php $select = Mage::getStoreConfig('paradoxlabs_autoship/autoship/default_period'); ?>
			<?php foreach( $opts as $k => $v ): ?>
				<option value="<?php echo $k; ?>" <?php if( $k == $select ): ?>selected="selected"<?php endif; ?>><?php echo $v; ?></option>
			<?php endforeach; ?>
		</select>
	</div>
<?php endif; ?>
