<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Rules
 */
?>
<?php /** @var Amasty_Rules_Block_Banner $this */?>
<?php /** @var Mage_SalesRule_Model_Rule $_rule */?>

<?php foreach($this->getValidRules() as $_rule) :?>
    <?php if ($this->getDescription($_rule) || $this->getImage($_rule)):?>
        <div class="<?php echo ($this->getPosition() == "top" ? "category-image" : "product-options")?>">
            <?php if ($this->getDescription($_rule)): ?>
                <div class="ampromo-desc">
                    <?php echo Mage::helper('cms')->getPageTemplateProcessor()->filter($this->getDescription($_rule)); ?>
                </div>
            <?php endif; ?>
            <?php $img = $this->getImage($_rule); ?>
            <?php if ($img) :?>
                <p class="ampromo-img">
                    <a href="<?php echo $this->getLink($_rule);?>" title="<?php echo $this->escapeHtml($this->getHoverText($_rule)) ?>">
                        <img src="<?php echo $img;?>" alt="<?php echo $this->escapeHtml($this->getAlt($_rule)) ?>" title="<?php echo $this->escapeHtml($this->getHoverText($_rule)) ?>" />
                    </a>
                </p>
            <?php endif; ?>
            <div style="clear: both;"></div>
        </div>
    <?php endif;?>
<?php endforeach; ?>


