<?php
/**
* Copyright 2016 aheadWorks. All rights reserved.
* See LICENSE.txt for license details.
*/

?>
<script type="text/x-magento-init">
    {
        ".aw-acp-popup__options-wrapper [data-role=swatch-options]": {
            "Magento_Swatches/js/swatch-renderer": {
                "selectorProduct": ".aw-acp-popup__form",
                "jsonConfig": <?php /* @noEscape */  echo $swatchOptions = $block->getJsonConfig(); ?>,
                "jsonSwatchConfig": <?php /* @noEscape */ echo $swatchOptions = $block->getJsonSwatchConfig(); ?>,
                "mediaCallback": "<?php /* @noEscape */ echo $block->getMediaCallback() ?>",
                "onlyMainImg": <?php /* @noEscape */ echo $block->getVar('change_only_base_image',
                    'Magento_Swatches') ?: 'false'; ?>
            }
        }
    }
</script>
<script type="text/x-magento-init">
    {
        ".aw-acp-popup__options-wrapper [data-role=swatch-options]": {
            "Aheadworks_Ajaxcartpro/js/ui/options/swatch-values-setter": {
                "values": <?php /* @noEscape */ echo $block->getSelectedSwatchesJson(); ?>
            }
        }
    }
</script>