<?php /** Herein, building the configurable option dropdowns allowing users to choose color, size, flavor, whatever the case. Supports anything Magento does. **/ ?>
<?php $profile	= $this->getProfile(); ?>
<?php $itemInfo	= $profile->getOrderItemInfo(); ?>
<?php if( $itemInfo['product_type'] == 'configurable' ): ?>
	<?php /** Load parent and child products from RP **/ ?>
	<?php $parent		= Mage::getModel('catalog/product')->load( $itemInfo['product_id'] ); ?>
	<?php $selected		= Mage::getModel('catalog/product')->loadByAttribute( 'sku', $itemInfo['sku'] ); ?>
	
	<?php /** Set parent as the active product (necessary for optionsPrice later) **/ ?>
	<?php Mage::register('product', $parent); ?>
	
	<?php /** Get the configurable options **/ ?>
	<?php $config		= $this->getLayout()->createBlock('catalog/product_view_type_configurable'); ?>
	<?php $config->setProduct( $parent ); ?>
	<?php $configJson	= $config->getJsonConfig(); ?>
	<?php $configArray	= json_decode( $configJson, 1 ); ?>
	
	<?php /** Build a super_attributes array to set default configurable values **/ ?>
	<?php $values 		= array( 'super_attribute' => array() ); ?>
	<?php foreach( $configArray['attributes'] as $attribute ): ?>
		<?php foreach( $attribute['options'] as $option ): ?>
			<?php if( $option['id'] == $selected->getData( $attribute['code'] ) ): ?>
				<?php $values['super_attribute'][ $attribute['id'] ] = $option['id']; ?>
				<?php continue; ?>
			<?php endif; ?>
		<?php endforeach; ?>
	<?php endforeach; ?>
	
	<?php /** Regenerate configurable options json **/ ?>
	<?php $parent->setPreconfiguredValues( new Varien_Object( $values ) ); ?>
	<?php $config->setProduct( $parent ); ?>
	<?php $configJson	= $config->getJsonConfig(); ?>
	
	<?php /** Output select boxes (values inserted on runtime) **/ ?>
	<?php foreach( $configArray['attributes'] as $attribute ): ?>
		<li class="item">
			<h4><?php echo $attribute['label'] ?></h4>
			<div class="input-box">
				<select name="super_attribute[<?php echo $attribute['id']; ?>]" id="attribute<?php echo $attribute['id']; ?>" class="required-entry super-attribute-select validate-select">
					<option value=""><?php echo $this->__('Choose an option...'); ?></option>
				</select>
			</div>
		</li>
	<?php endforeach; ?>
	
	<?php /** Output JS data to tie everything together **/ ?>
	<script type="text/javascript">
	//<![CDATA[
    	var optionsPrice = new Product.OptionsPrice(<?php echo $this->getLayout()->createBlock('catalog/product_view')->setProduct( $parent )->getJsonConfig(); ?>);
		var spConfig = new Product.Config(<?php echo $configJson; ?>);
	//]]>
	</script>
<?php endif; ?>
