<?php $profile	= $this->getProfile(); ?>
<?php $itemInfo	= $profile->getOrderItemInfo(); ?>
<?php $product	= Mage::getModel('catalog/product')->load( $itemInfo['product_id'] ); ?>
<?php if( $product && $product->getId() == $itemInfo['product_id'] && $product->getData('allow_autoship') == 1 ): ?>
	<li class="item">
		<h4><?php echo $this->__('Frequency') ?></h4>
		<div class="input-box">
			<select name="subscription_period" id="subscription_period">
				<?php foreach( Mage::app()->getLayout()->createBlock('autoship/product_option')->getOptions() as $k => $v ): ?>
					<?php if( $k < 1 ) continue; ?>
					<option value="<?php echo $k; ?>" <?php if( $k == $this->getProfile()->getPeriodFrequency() ): ?>selected="selected"<?php endif; ?>><?php echo $v; ?></option>
				<?php endforeach; ?>
			</select>
		</div>
	</li>
<?php endif; ?>
