<?php
              // some helpers
              $_helper = $this->helper('catalog/output');
              $storeId = Mage::app()->getStore()->getId();
              $catalog = $this->getLayout()->createBlock('catalog/product_list')->setStoreId($storeId);
              $productCount = $this->getData('num_products');

$visibility = array(
                    Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,
                    Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
                );

  if(true == true){
$collection = Mage::getResourceModel('reports/product_collection')
                      ->addAttributeToSelect('*')
                      ->setStoreId($storeId)
                      ->addStoreFilter($storeId)
                      ->addAttributeToFilter('visibility', $visibility)
                      ->setPageSize($productCount);
Mage::getSingleton('cataloginventory/stock')->addInStockFilterToCollection($collection);


/*  To display product by category id */
if($categoryId=$this->getData('category_id')){
      $category = Mage::getModel('catalog/category')->load($categoryId);
      $collection->addCategoryFilter($category);
    } ?>

  <div class="new_title center">
    <?php if ($category) { ?>
      <h2><?php echo $category->getName() ?></h2>
    <?php } ?>
  </div> <!--new_title center-->

<?php             // if no products are currently recommended, display some text
              if (!$collection->count()) :
?>
      <p class="note-msg"><?php echo $this->__('There are no recommended products at the moment.') ?></p>
      <?php else : ?>

      <a id="product_slider_prev" class="jcarousel-prev-horizontal2" href="#"></a> <a id="product_slider_next" class="jcarousel-next-horizontal2" href="#"></a>
        <div class="jcarousel-skin-tango5">
          <div class="jcarousel-container jcarousel-container-horizontal" style="position: relative; display: block;">
            <div class="jcarousel-clip jcarousel-clip-horizontal" style="overflow: hidden; position: relative;">
              <ul class="products-grid jcarousel-list jcarousel-list-horizontal" id="product_slider" style="overflow: hidden; position: relative; top: 0px; margin: 0px; padding: 0px; left: -768px; width: 4156px;">
        <?php
                $_collectionSize = $collection->count();
                $_columnCount = 6;
                $i = 0;

                foreach ($collection as $_product) :
                        $_product = Mage::getModel('catalog/product')->setStoreId($storeId)->load($_product->getId());

        ?>

        <?php if ($i++%$_columnCount==0): ?>
        <?php endif ?>
    <li class="item">
   <div class="item-inner">

      <?php echo $this->helper('eclipsesettings')->getLabel($_product);  ?>
      <div class="pro-img-thumb">
         <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><img alt="<?php echo $this->htmlEscape($_product->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(172,172) ?>"></a>
      </div> <!--pro-img-thumb-->
      <div class="actions-links">
        <span class="add-to-links">
          <?php  if(Mage::app()->getStore()->getConfig('eclipsesettings/eclipsesettings_quickview/enable')==1){?>
           <a title="magik-btn-quickview" class="magik-btn-quickview" data-fancybox-type="ajax" onclick="callQuickView('<?php echo Mage::getUrl('eclipsesettings/index/view/id/'.$_product->getId());?>');"><span><?php echo $this->__('quickview') ?></span></a>
          <?php }  ?>
           <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist');?>"><span><?php echo $this->__('Add to Wishlist');?></span></a>
            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                    <a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare');?>"><span><?php echo $this->__('Add to Compare');?></span></a>
            <?php endif; ?>
        </span> <!--add-to-links-->
      </div> <!--actions-links-->

    <div class="item-info">
      <div class="info-inner">
         <div class="item-title">
             <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                  <?php $prod_name = $this->htmlEscape($_product->getName()) ;
                  if(strlen($prod_name) > 87) {echo substr($prod_name,0,87)."...";}else {echo $prod_name;}?>
             </a>
          </div> <!--item-title-->
          <div class="item-content">
            <?php
                        $summaryData = Mage::getModel('review/review_summary')
                                ->setStoreId($storeId)
                                ->load($_product->getId());
                        if($summaryData->getRatingSummary()){ ?>
                            <div class="ratings">
                                <div class="rating-box">
                                        <div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>"></div>
                                </div> <!--rating-box-->
                            </div> <!--ratings-->
                    <?php } else { ?>
                            <div class="ratings"><div class="rating-box"><div style="width:0%" class="rating"></div></div></div>
                    <?php } ?>
            <div class="item-price"><?php echo $this->getPriceHtml($_product, true) ?></div>
          </div> <!--item-content-->
      </div> <!--info-inner-->
      <div class="actions">
            <?php if($_product->isSaleable()): ?>
              <button type="button"  title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
            <?php else: ?>
              <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>
        </div> <!--actions-->
    </div> <!--item-info-->
   </div> <!--item-inner-->
</li> <!--item jcarousel-item jcarousel-item-horizontal jcarousel-item-1 jcarousel-item-1-horizontal-->
            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            <?php endif ?>
                <?php endforeach ?>
       </ul>
     </div> <!--jcarousel-clip jcarousel-clip-horizontal-->
   </div> <!--jcarousel-container jcarousel-container-horizontal-->
 </div> <!--jcarousel-skin-tango5-->

      <?php endif ?>  <!--Endif !$collection->count() -->

<?php } ?> <!-- chk attribute_code -->

<script type="text/javascript">
jQuery(document).ready(function($) {

  function mycarousel_initCallback(carousel) {

      jQuery('#product_slider_next').bind('click', function() {
          carousel.next();
          return false;
      });
      jQuery('#product_slider_prev').bind('click', function() {
          carousel.prev();
          return false;
      });
  };

    jQuery('#product_slider').jcarousel({
      scroll: 1,
      initCallback: mycarousel_initCallback,
      buttonNextHTML: null,
      buttonPrevHTML: null
    });
});
</script>

<div id="mgkquickview3">
<div id="magikloading3" style="display:none;text-align:center;margin-top:400px;"><img src="<?php echo $this->getSkinUrl('images/mgkloading.gif');?>" alt="loading">
</div></div>
<script type="text/javascript">
function callQuickView(qurl) {
    jQuery('#mgkquickview3').show();
    jQuery('#magikloading3').show();
    jQuery.get(qurl, function(data) {
      jQuery.fancybox(data);
      jQuery('#magikloading3').hide();
jQuery('#mgkquickview3').hide();
    });
 }
 </script>
