<?php
$getmgkDiffshipaddress=Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcgeneral_group/mgkshiptodiffadd');
$getmgkStreetlines=$this->helper('customer/address')->getStreetLines();
$getmgkAddress=Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcfield_group/mgkopcaddress');
$getmgkCompany=Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcfield_group/mgkopccompany');
$getmgkCountry=Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcfield_group/mgkshowcountry');
$getmgkCity=Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcfield_group/mgkopccity');
$getmgkZip=Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcfield_group/mgkopczip');
$getmgkState=Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcfield_group/mgkopcstate');
$getmgkPhone=Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcfield_group/mgkopcphone');
$getmgkFax=Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcfield_group/mgkopcfax');
$getmgkDOB=Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcfield_group/mgkopcdob');
$getmgkTax=Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcfield_group/mgkopctax');
$getmgkGender=Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcfield_group/mgkopcgender');
$getmgkAllowGuest=Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcgeneral_group/mgkallowguest');
?>
<div class="mgkosc-frame">
    <div class="mgkosc-frametitle"><?php echo $this->__('Billing Address'); ?></div>
    <div class="mgkosc-framecontent">
    <?php if ($this->customerHasAddresses()): ?>
        <div class="mgkosc-wide">
            <label for="billing_cutomer_address">
            	<?php echo $this->__('Select a billing address from your address book or enter a new address.') ?>
            </label>
            <div class="mgkosc-box">
                <?php echo $this->getAddressesHtmlSelect('billing');?>
            </div>
        </div>
    <?php endif; ?>
	    <div id="mgkosc-billingform" style="display:<?php echo $this->customerHasAddresses()? 'none': 'block'; ?>">
			<input type="hidden" name="billing[address_id]" id="billing:address_id" value="<?php echo $this->getmgkBillingAddress()->getId() ?>" />
			<div class="mgkosc-fields">
				<?php echo $this->getLayout()->createBlock('onestepcheckout/widget_name')->setObject($this->getmgkBillingAddress())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
			</div>
			<div class='clr'></div>
			<?php if(!$this->isCustomerLoggedIn()): ?>
			<div class="mgkosc-wide">
			      <label for="billing:email"><?php echo $this->__('Email Address') ?><em class="required"> * </em></label>
			      <div class="mgkosc-box">
				    <input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="mgkosc-input-text validate-email required-entry" />
			      </div>
			</div>
			<?php endif; ?>
			<div class="mgkosc-wide" <?php if($getmgkCompany == 'no'){ echo ' style="display:none" ';}?>>
			      <label for="billing:company"><?php echo $this->__('Company') ?><?php if ($getmgkCompany=='req') echo ' <em class="required">*</em>' ?></label>
			      <div class="mgkosc-box">
				    <input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="mgkosc-input-text <?php if($getmgkCompany == 'req'){ echo ' required-entry';} ?>" />
			      </div>
			</div>
			 
			<div class="mgkosc-wide" <?php if($getmgkAddress == 'no'){ echo ' style="display:none" ';}?>>
			      <label for="billing:street1"><?php echo $this->__('Address') ?><?php if ($getmgkAddress=='req') echo '<em class="required">*</em>' ?></label>
			      <div class="mgkosc-box">
				    <input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="mgkosc-input-text <?php if($getmgkAddress == 'req') { echo ' required-entry';}?>" />
			      </div>
			</div>
			<?php 	
				$address2 = $getmgkStreetlines;
				for ($i = 2; $i <= $address2; $i++){ 
			?>
			<div class="mgkosc-wide" <?php if($getmgkAddress == 'no'){ echo ' style="display:none" ';}?>>
			      <div class="mgkosc-box">
				    <input type="text" name="billing[street][]" id="billing:street<?php echo $i?>" title="<?php echo $this->__('Street Address %s', $i) ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($i)) ?>" class="mgkosc-input-text" />
			      </div>
			</div>
			<?php } ?>

			<div class="mgkosc-fields" >
			      <div class="mgkosc-field" <?php if($getmgkCity == 'no'){ echo ' style="display:none" ';}?>>
				      <label for="billing:city"><?php echo $this->__('City') ?><?php if ($getmgkCity=='req') echo ' <em class="required">*</em>' ?></label>
				      <div class="mgkosc-box">
					  <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="mgkosc-input-text <?php if($getmgkCity == 'req') { echo ' required-entry';}?>" id="billing:city" />
				      </div>
				</div>
				<div class="mgkosc-field" <?php if($getmgkState == 0){ echo ' style="display:none" ';}?>>
				    <label for="billing:region_id"><?php echo $this->__('State/Province') ?></label>
				    <div class="mgkosc-box">
					  <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select <?php if($getmgkState == 1){ echo ' required-entry';}?>" style="display:none;width:105px;">
					      <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
					  </select>
					  <script type="text/javascript">
					    //<![CDATA[
					    $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getmgkBillingAddress()->getRegionId() ?>");
					    //]]>
					  </script>
					  <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->escapeHtml($this->getmgkBillingAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="mgkosc-input-text " style="display:none;" />
				    </div>
				</div>
			</div>
			<div class='clr'></div>
			
			<?php if ($getmgkZip != 'no' || $getmgkPhone != 'no') : ?>
			<div class="mgkosc-fields" >
			    <?php if ($getmgkZip != 'no') : ?>
			      <div class="mgkosc-field" >
				  <label for="billing:postcode"><?php echo $this->__('Zip/Postal Code') ?><?php if ($getmgkZip=='req') echo ' <em class="required">*</em>' ?></label>
				  <div class="mgkosc-box">
					<input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="mgkosc-input-text validate-zip-international <?php if($getmgkZip == 'req'){ echo ' required-entry';}?>" />
				  </div>
			      </div>
			      <?php endif ?>
			      <?php if ($getmgkPhone != 'no') : ?>
			      <div class="mgkosc-field" >
				  <label for="billing:telephone"><?php echo $this->__('Telephone') ?><?php if ($getmgkPhone=='req') echo ' <em class="required">*</em>' ?></label>
				  <div class="mgkosc-box">
				    <input type="text" name="billing[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="mgkosc-input-text <?php if($getmgkPhone=='req') { echo ' required-entry validate-number';}?>" id="billing:telephone" />
				  </div>
			      </div>
			      <?php endif ?>
			</div>
			<div class='clr'></div>
			<?php endif ?>

			<div class="mgkosc-wide" <?php if($getmgkCountry == 0){ echo ' style="display:none" ';}?>>
			      <label for="billing:country_id"><?php echo $this->__('Country') ?><?php if ($getmgkCountry==1) echo ' <em class="required">*</em>' ?></label>
			      <div class="mgkosc-box">
				  <?php echo $this->getmgkCountryHtmlSelect('billing') ?>
			      </div>
			</div>
			
			<div class="mgkosc-fields" <?php if($getmgkFax == 'no'){ echo ' style="display:none" ';}?>>
			    <div class="mgkosc-field" >
				<label for="billing:fax"><?php echo $this->__('Fax') ?><?php if ($getmgkFax=='req') echo ' <em class="required">*</em>' ?></label>
				<div class="mgkosc-box">
				      <input type="text" name="billing[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="mgkosc-input-text <?php if($getmgkFax == 'req') {echo ' required-entry ';}?>" id="billing:fax" />
				</div>
			    </div>
			</div>
			<div class='clr'></div>
			 <?php if(!$this->isCustomerLoggedIn()): ?>
			      <?php $_dob = $this->getLayout()->createBlock('onestepcheckout/widget_dob') ?>
			      <?php $_gender = $this->getLayout()->createBlock('onestepcheckout/widget_gender') ?>
			      <div class="mgkosc-fields">
				    <?php if ( $_dob->isEnabled() ): ?>
					  <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
				    <?php endif ?>
				    <?php if ( $_gender->isEnabled() ): ?>
					  <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
				    <?php endif ?>
			      </div>
			      <div class='clr'></div>


			      <?php $_taxvat = $this->getLayout()->createBlock('onestepcheckout/widget_taxvat') ?>
			      <?php if ( $_taxvat->isEnabled() ): ?>
				  <div class="mgkosc-wide">
				      <?php echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
				  </div>
			      <?php endif ?>
			      <?php if ($getmgkAllowGuest){ ?>
				    <div class="mgkosc-fields">
					<input type="checkbox" name="billing[register_account]" value="1" title="<?php echo $this->__('Create an account for later use') ?>" id="billing:register_account" onclick="if(window.billing) billing.setCreateAccount(this.checked);"<?php if ($this->getmgkBillingAddress()->getRegisterAccount()):?> checked="checked"<?php endif;?> class="checkbox" />
					<label for="billing:register_account"><?php echo $this->__('Create an account for later use') ?></label>
				    </div>
			      <?php } else{ ?>
					<input type="hidden" name="billing[register_account]" value="1"/>
			      <?php } ?>
			      <div class="mgkosc-fields" id="register-customer-password" <?php if ($getmgkAllowGuest) { echo ' style="display: none;" '; } ?>>
				  <div class="mgkosc-field">
				      <label for="billing:customer_password"><?php echo $this->__('Password') ?><em class="required"> * </em></label>
				      <div class="mgkosc-box">
					  <input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="mgkosc-input-text required-entry validate-password" />
				      </div>
				  </div>
				  <div class="mgkosc-field">
				      <label for="billing:confirm_password"><?php echo $this->__('Confirm Password') ?><em class="required"> * </em></label>
				      <div class="mgkosc-box">
					  <input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="mgkosc-input-text required-entry validate-cpassword" />
				      </div>
				  </div>
			      </div>
			<?php endif; ?>
			
			<?php 
			      if ($getmgkDiffshipaddress && $this->canShip()){ 
			?>
			    <input type="hidden" name="billing[use_for_shipping]" id="billing:use_for_shipping" value="<?php echo ($this->isUseBillingAddressForShipping())?'1':'0'; ?>" />
			<?php } else { ?>
			    <input type="hidden" name="billing[use_for_shipping]" value="1" />
			<?php } ?>
			
	        
			
	</div><!--mgkosc-billingform close-->
	<?php if(!$this->getQuote()->isVirtual() && $getmgkDiffshipaddress): ?>
			     <div class="mgkosc-fields">
				    <input type="checkbox" class="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1" <?php if($this->getQuote()->getShippingAddress()->getSameAsBilling()){echo ' checked="checked" ';} ?> title="<?php echo $this->__('Ship to this address') ?>" onclick="shipping.setSameAsBilling(this.checked)" />
				    <label><?php echo $this->__('Ship to this address') ?></label>
			      </div>
		      <?php endif; ?>
    </div><!--mgkosc-framecontent close-->
</div>
<script type="text/javascript">
//<![CDATA[
	var billing = new BillingAddress();
	RegionUpdater.prototype.setMarkDisplay = function(){};
	ZipUpdater.prototype._setPostcodeOptional = function(){};
	var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions, undefined, 'billing:postcode');
//]]>
</script>