<?php
?>
<div id="checkout-review" class="mgkosc-frame">
    <div class="mgkosc-frametitle"><?php echo $this->__('Review Your Order') ?></div>
    <div class="mgkosc-framecontentinfo">
	<div id="checkout-review-load"><?php echo $this->getChildHtml('info') ?></div>
    </div>
    <?php if (Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcgeneral_group/mgknewssub')) : ?>
	    <div class="mgkosc-newsletter-subscribe">
		<input type="checkbox" value="1" id="newsletter-signup"  name="newsletter"  title="<?php echo Mage::helper('newsletter')->__('Sign up for our newsletter') ?>">
                <label for="subscribe_to_newsletter"><?php echo Mage::helper('newsletter')->__('Sign up for our newsletter') ?></label>
	    </div>	
    <?php endif; ?>

    <?php if (Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcgeneral_group/mgkcomment')) : ?>
	    <div class="mgkosc-comment">
		  <strong><?php echo $this->__('Your Comment for this Order') ?></strong>
		  <div id="comment-block" class="data_area">
		      <textarea id="order-comment" name="order-comment" rows="5" cols="81"></textarea>
		  </div>
		 
	    </div>
    <?php endif; ?>
    <?php if (Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcgeneral_group/mgkopccoupon')) : ?>		       
	  <div id="checkout-coupon-discount-load" class="mgkosc-couponcode">
            <?php echo $this->getChildHtml('coupon') ?>
        </div>
    <?php endif; ?>
    <div class="clr"></div>
    
    
    <div id="checkout-review-submit">
	    <?php echo $this->getChildHtml('agreements') ?>
	    <div class="buttons-set" id="review-buttons-container" style="border-top:0px;margin:0px;">
		<?php if (Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcgeneral_group/mgkcartlink')) : ?>
		     
		      <p class="mgkosc-cartlink"><?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>"><?php echo $this->__('Edit Your Cart') ?></a></p>
		      
		<?php endif; ?>
		<button type="submit" title="<?php echo $this->__('Place Order') ?>" class="button btn-checkout" onclick="checkout.save(); return false;"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
		
		<span class="mgkoscplease-wait" id="review-please-wait" style="display:none;">
		    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Submitting order information...') ?>" title="<?php echo $this->__('Submitting order information...') ?>" class="v-middle" /> <?php echo $this->__('Submitting order information...') ?>
		</span>
	    </div>
    </div>
</div>
