<?php
$getmgkDiffshipaddress=Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcgeneral_group/mgkshiptodiffadd');
$getmgkStreetlines=$this->helper('customer/address')->getStreetLines();
$getmgkAddress=Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcfield_group/mgkopcaddress');
$getmgkCompany=Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcfield_group/mgkopccompany');
$getmgkCountry=Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcfield_group/mgkshowcountry');
$getmgkCity=Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcfield_group/mgkopccity');
$getmgkZip=Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcfield_group/mgkopczip');
$getmgkState=Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcfield_group/mgkopcstate');
$getmgkPhone=Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcfield_group/mgkopcphone');
$getmgkFax=Mage::getStoreConfig('mgkonestepcheckout_section/mgkopcfield_group/mgkopcfax');

if(!$this->getQuote()->isVirtual() && $getmgkDiffshipaddress) {
?>
<div id="ship_address_block" class="mgkosc-frame" <?php if($this->getQuote()->getShippingAddress()->getSameAsBilling()){echo 'style="display: none;"';}?>>
      <div class="mgkosc-frametitle"><?php echo $this->__('New Shipping Address') ?></div>
      <div class="mgkosc-framecontent">
	  <?php if ($this->customerHasAddresses()): ?>
		<div class="mgkosc-wide">
		    <label><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>
		    <div class="mgkosc-box"><?php echo $this->getAddressesHtmlSelect('shipping');?></div>
		</div>
	  <?php endif; ?>
	  <div id="mgkosc-shppingform" style="display:<?php echo $this->customerHasAddresses()? 'none': 'block'; ?>">
		<input type="hidden" name="shipping[address_id]" id="shipping:address_id" value="<?php echo $this->getmgkShipingAddress()->getId() ?>" />
		<div class="mgkosc-fields">
		      <?php echo $this->getLayout()->createBlock('onestepcheckout/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?>
		</div>
		<div class='clr'></div>
		<div class="mgkosc-wide" <?php if($getmgkCompany == 'no'){ echo ' style="display:none" ';}?>>
		    <label for="shipping:company"><?php echo $this->__('Company') ?><?php if ($getmgkCompany=='req') echo ' <em class="required">*</em>' ?></label>
		    <div class="mgkosc-box">
			<input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="mgkosc-input-text <?php if( $getmgkCompany == 'req' ){ echo ' required-entry ';} ?>" onchange="shipping.setSameAsBilling(false);" />
		    </div>
		</div>
		<div class="mgkosc-wide" <?php if($getmgkAddress == 'no'){ echo ' style="display:none" ';}?>>
		    <label for="shipping:street1"><?php echo $this->__('Address') ?><?php if ($getmgkAddress=='req') echo ' <em class="required">*</em>' ?></label>
		    <div class="mgkosc-box">
			  <input type="text" title="<?php echo $this->__('Street Address') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="mgkosc-input-text <?php if($getmgkAddress == 'req'){echo ' required-entry';}?>" onchange="shipping.setSameAsBilling(false);" />
		    </div>
		</div>
		<?php 	
		  $address2	= $getmgkStreetlines;
		  for ($i = 2; $i <= $address2; $i++){ 
		?>
		<div class="mgkosc-wide" <?php if($getmgkAddress == 'no'){ echo ' style="display:none" ';}?>>
		  <div class="mgkosc-box">
			<input type="text" name="shipping[street][]" id="shipping:street<?php echo $i?>" title="<?php echo $this->__('Street Address %s', $i) ?>" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet($i)) ?>" class="mgkosc-input-text" onchange="shipping.setSameAsBilling(false);" />
		  </div>
		</div>
		<?php } ?>
	      
		<div class="mgkosc-fields" >
		    <div class="mgkosc-field" <?php if($getmgkCity == 'no'){ echo ' style="display:none" ';}?>>
			<label for="shipping:city"><?php echo $this->__('City') ?><?php if ($getmgkCity=='req') echo ' <em class="required">*</em>' ?></label>
			<div class="mgkosc-box">
			      <input type="text" name="shipping[city]" id="shipping:city" title="<?php echo $this->__('City') ?>" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="mgkosc-input-text validate-alpha <?php if ($getmgkCity == 'req'){ echo ' required-entry ';}?>" onchange="shipping.setSameAsBilling(false);"  />
			</div>
		    </div>
		    <div class="mgkosc-field" <?php if($getmgkState == 0){ echo ' style="display:none" ';}?>>
			<label for="billing:region_id"><?php echo $this->__('State/Province') ?></label>
			<div class="mgkosc-box">
			    <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;width:105px;">
				<option value=""><?php echo $this->__('Please select region, state or province') ?></option>
			    </select>
				  <script type="text/javascript">
				  //<![CDATA[
				      $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getmgkShipingAddress()->getRegionId() ?>");
				  //]]>
				  </script>
				  <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->htmlEscape($this->getmgkShipingAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="mgkosc-input-text" style="display:none;"  />

			</div>
		  </div>
	      </div>
	      <div class='clr'></div>
	     

		<?php if ($getmgkZip != 'no' || $getmgkPhone != 'no') : ?>
		      <div class="mgkosc-fields" <?php if($getmgkZip == 'no'){ echo ' style="display:none" ';}?>>
			  <div class="mgkosc-field" >
			      <label for="shipping:postcode"><?php echo $this->__('Zip/Postal Code') ?><?php if ($getmgkZip=='req') echo ' <em class="required">*</em>' ?></label>
			      <div class="mgkosc-box">
				  <input type="text" name="shipping[postcode]" id="shipping:postcode" title="<?php echo $this->__('Zip/Postal Code') ?>" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" class="mgkosc-input-text validate-zip-international<?php if($getmgkZip == 'req'){echo ' required-entry ';}?>"  onchange="shipping.setSameAsBilling(false);" />
			      </div>
			  </div>
		      </div>
		      <div class="mgkosc-fields" <?php if($getmgkPhone == 'no'){ echo ' style="display:none" ';}?>>
			  <div class="mgkosc-field" >
			      <label for="shipping:telephone"><?php echo $this->__('Telephone') ?><?php if ($getmgkPhone=='req') echo ' <em class="required">*</em>' ?></label>
			      <div class="mgkosc-box">
				      <input type="text" name="shipping[telephone]" id="shipping:telephone" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="mgkosc-input-text <?php if($getmgkPhone == 'req') { echo ' required-entry validate-number ';}?>"  onchange="shipping.setSameAsBilling(false);" />
			      </div>
			  </div>
		      </div>
		<?php endif ?>
		<div class="mgkosc-wide" <?php if($getmgkCountry == 'no'){ echo ' style="display:none" ';}?>>
                     <label for="shipping:country_id"><?php echo $this->__('Country') ?><?php if ($getmgkCountry=='req') echo ' <em class="required">*</em>' ?></label>
                     <div class="mgkosc-box">
                            <?php echo $this->getmgkCountryHtmlSelect('shipping') ?>
                     </div>
		</div>
		
		<div class="mgkosc-fields" <?php if($getmgkFax == 'no'){ echo ' style="display:none" ';}?>>
		    <div class="mgkosc-field">
			<label for="shipping:fax"><?php echo $this->__('Fax') ?><?php if ($getmgkFax=='req') echo ' <em class="required">*</em>' ?></label>
			<div class="mgkosc-box">
			      <input type="text" name="shipping[fax]" id="shipping:fax" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="mgkosc-input-text<?php if($getmgkFax == 'req') {echo ' required-entry ';}?>" onchange="shipping.setSameAsBilling(false);" />
			</div>
		    </div>
		</div>
		<div class='clr'></div>
	  </div>
      </div>
</div>
<script type="text/javascript">
//<![CDATA[
	var shipping = new ShippingAddress('mgkosc_form');
	var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions, undefined, 'shipping:postcode');
//]]>
</script>
<?php 
} 
?>