<?php if (isset($_SERVER) && isset($_SERVER["REQUEST_METHOD"])) { ?>
<?php if (file_exists($_SERVER['DOCUMENT_ROOT'] . '/app/Mage.php')) { ?>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="/skin/frontend/rwd/eclipse/images/landing-pages/preferences/css/grid.css">
  <div class="w-section email-pref-header"><img width="332" src="/skin/frontend/rwd/eclipse/images/landing-pages/preferences/images/573382290bec74851deb2842_BL-logo-v4-400.png">
  </div>

  <?php
  require_once $_SERVER['DOCUMENT_ROOT'] . '/app/Mage.php';

  // gather query parameters
  $method = $_SERVER["REQUEST_METHOD"];
  $first = $_GET['first'];
  $last = str_replace('"', "", $_GET['last']);
  $email = $_GET['email'];
  $campaign_code = $_GET['campaign_code'];
  $token = $_GET['token'];
  $password = $_POST['name'];

  define('SYSTEM_ID', 'SHOP');

  // include library
  include($_SERVER['DOCUMENT_ROOT'] . "/CDH.php");
  $cdh = new CDH($_SERVER["ESB_URL"]);

  // check token for security
  if ($token !== $cdh->get_token($email, $campaign_code)) {
      syslog(LOG_ALERT,
        'bad link token received for email:' . $email .
        '  expected:' . $cdh->get_token($email, $campaign_code) .
        '  received:' . $token .
        '  request was:' . $_SERVER['QUERY_STRING'] );
      Mage::app()->getFrontController()->getResponse()->setRedirect(Mage::getBaseUrl())->sendResponse();
      exit;
      }

if ( strcmp($method, 'POST') == 0 ) {
      $magento_id = $cdh->set_user($email, $password, $first, $last);
      $base = Mage::getBaseUrl();
      syslog(LOG_INFO, 'Mag:'.$magento_id.  ' cam:' .$campaign_code );
      $url = $base . 'email-preferences'.
          '?token='. $token.
          '&email='. $email.
          '&first='. $first.
          '&last='. $last.
          '&campaign_code='.$campaign_code.
          '&magento_id='. $magento_id;
      syslog(LOG_INFO, $url);
      echo '<META HTTP-EQUIV=REFRESH CONTENT="1; '.$url.'">';
      exit;
      }
  ?>

  <div class="w-section form-section">
    <div class="w-container">
      <div class="w-form">
        <form id="email-form" name="email-form" data-name="Email Form" method="post">
            <label for="first">First Name:</label>
            <input id="first" type="name" placeholder="Enter your first name" name="first" data-name="first" required="required" class="w-input" value="<?php echo $first;?>">
            <label for="last">Last Name:</label>
            <input id="last" type="last" placeholder="Enter your last name" name="last" data-name="last" required="required" class="w-input" value="<?php echo $last;?>">
            <label for="email">Email Address:</label>
            <input id="email" type="email" placeholder="Enter your email address" name="email" data-name="Email" required="required" class="w-input" value="<?php echo $email;?>">
          <label for="name">Choose a Password</label>
          <input id="name" type="password" placeholder="Enter a password" name="name" data-name="Name" class="w-input">
          <div style="width:100%; text-align:center !important; margin-left:auto !important; margin-right:auto !important;"><input style=" font-size:16px !important;" type="submit" value="Submit" data-wait="Please wait..." class="w-button"></div>
        </form>
        <div class="w-form-done">
          <p>Thank you! Your submission has been received!</p>
        </div>
        <div class="w-form-fail">
          <p>Oops! Something went wrong while submitting the form</p>
        </div>
      </div>
    </div>
  </div>
  <?php } ?>
  <?php } ?>
