
<?php
$_element = $this->getElement();
?>
<div class="rule-tree">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $_element->getLegend() ?></h4>
    </div>
    <fieldset id="<?php echo $_element->getHtmlId() ?>" <?php echo $_element->serialize(array('class')) ?>>

	<?php if ($_element->getComment()): ?>
    	<p class="comment"><?php echo $this->escapeHtml($_element->getComment()) ?></p>
	<?php endif; ?>
	<?php echo $_element->getChildrenHtml() ?>
    </fieldset>
</div>
<script type="text/javascript">
//<![CDATA[
<?php echo $_element->getHtmlId() ?> = new VarienRulesForm('<?php echo $_element->getHtmlId() ?>', '<?php echo $this->getNewChildUrl() ?>');
//]]>
</script>
<?php if ($this->getDebugMode() && mage::getIsDeveloperMode()): ?>
    <div class="debug"><?php Zend_Debug::dump(unserialize($this->getRawRuleData()), 'RAW RULE DATA', true); ?></div>
<?php endif; ?>
