<?php if (Mage::getStoreConfig('dyncatprod/rebuild/delayed')): ?>
<ul class="messages"><li class="warning-msg">
        <ul>
            <li>
                <span>Delayed category building is enabled in configuration. The category dynamic products will rebuild via cron in a 5 minute cycle after this category is saved.</span>
            </li>
        </ul>
    </li>
</ul>
<?php endif; ?>
<?php if (Mage::getStoreConfig('dyncatprod/debug/enabled')): ?>
<ul class="messages"><li class="warning-msg">
        <ul>
            <li>
                <span>Debug Mode is enabled in configuration. This can slow down the build process. If debug is not required, disabled in configuration to speed things up.</span>
            </li>
        </ul>
    </li>
</ul>
<?php endif; ?>
<div class="entry-edit">
    <?php echo $this->getChildHtml('category_dyncatprod_rules'); ?>
</div>


