<?php /* This script inserts a number of elements required by the CIM Hosted popup right before the end of the page. */ ?>

<div id="divAuthorizeNetPopup" style="display:none;" class="AuthorizeNetPopupSimpleTheme">
	<div class="AuthorizeNetPopupOuter">
		<div class="AuthorizeNetPopupTop">
			<div class="AuthorizeNetPopupClose">
				<a href="#" onclick="AuthorizeNetPopup.closePopup(); return false;"><?php echo $this->__('Close'); ?></a>
			</div>
		</div>
		<iframe name="iframeAuthorizeNet" id="iframeAuthorizeNet" src="<?php echo $this->getUrl( 'authnetcim/ajax/empty', array( '_secure' => true ) ); ?>" frameborder="0" scrolling="no" style="vertical-align:middle"></iframe>
		<div class="AuthorizeNetPopupBottom">
			<div class="AuthorizeNetPopupLogo"></div>
		</div>
	</div>
	<div class="AuthorizeNetShadow AuthorizeNetShadowT"></div>
	<div class="AuthorizeNetShadow AuthorizeNetShadowR"></div>
	<div class="AuthorizeNetShadow AuthorizeNetShadowB"></div>
	<div class="AuthorizeNetShadow AuthorizeNetShadowL"></div>
	<div class="AuthorizeNetShadow AuthorizeNetShadowTR"></div>
	<div class="AuthorizeNetShadow AuthorizeNetShadowBR"></div>
	<div class="AuthorizeNetShadow AuthorizeNetShadowBL"></div>
	<div class="AuthorizeNetShadow AuthorizeNetShadowTL"></div>
</div>
<div id="divAuthorizeNetPopupScreen" style="display:none;" onclick="AuthorizeNetPopup.closePopup(); return false;"></div>
