<?php $hint = htmlspecialchars(trim($this->getField()->getHint())); ?>
<input type='text' name='<?php echo $this->getFieldName() ?>' id='<?php echo $this->getFieldId() ?>'
       class='<?php echo $this->getFieldClass() ?>' style='<?php echo $this->getFieldStyle() ?>'
       value="<?php echo htmlspecialchars($this->getFieldValue()); ?>"
       aria-labelledby="label_<?php echo $this->getFieldId() ?>"
       <?php if($this->getField()->getRequired()) {?>required<?php }?>
       <?php if ($this->getField()->getType() == 'email'){ ?>onkeyup="if(this.value.search(' ')>=0){this.value = this.value.replace(' ','');}"<?php } ?>
    <?php if ($this->getField()->getDisabled()) { ?> disabled <?php } ?>
       placeholder="<?php echo $hint?>"/>