  <meta name="viewport" content="width=device-width, initial-scale=1">

  <?php
  require_once $_SERVER['DOCUMENT_ROOT'] . '/app/Mage.php';

  // gather query parameters
  $method = $_SERVER["REQUEST_METHOD"];

  // iframe query params
  $color = $_GET['color'];
  $img = $_GET['img'];
  $sb_img = $_GET['sb_img'];
  $code = $_GET['code'];
  $name = $_GET['name'];
  $text = $_GET['text'];
  $bcolor = $_GET['bcolor'];
  
  // Form variables
  $first = $_POST['FIRSTNAME'];
  $last = $_POST['LASTNAME'];
  $email = $_POST['Email'];

  ?>

  <style type="text/css">
      FORM {
          background-color: transparent;
      }
      FORM .fieldLabel {
          font-family: Arial; font-size: 11px; color: #000000; font-weight: bold; text-decoration: none; font-style: normal;
      }
      FORM .yesNoCheckboxLabel {
          display: block;
          padding-left: 20px;
          text-indent: -20px;
      }
      FORM .fieldLabel .required {
          color: #CC0000 !important;
      }
      FORM .sectionHeader {
          font-family: Arial; font-size: 16px; color: #000000; font-weight: bold; text-decoration: none; font-style: normal;
      }
      FORM .paragraph {
          font-family: Arial; font-size: 10px; color: #000000; font-weight: normal; text-decoration: none; font-style: normal;
      }
      FORM TD, FORM .defaultText {
          font-family: Arial, Helvetica, sans-serif;
          font-size: 11px;
          color: black;
      }
      /**
      HACK FOR IE: IE always adds extra space to make an input huge and weird. this will
      force it to truncate our label and not keep the extra spaces.
      **/
      * HTML .buttonStyle {
          width: 1px;
          overflow:visible;
          padding-left: 5px;
          padding-right: 5px;
      }
      FORM .textInput {
          border: 1px solid #B5B8C8;
          padding:1px 3px;
      }
      FORM .selectInput {
          border: 1px solid #B5B8C8;
      }
      FORM .formErrorMessages DIV {
          font-family: Arial; font-size: 11px; color: #CC0000; font-weight: normal; text-decoration: none; font-style: normal;
          margin: 0 0 2px 7px;
      }
      FORM .formControlError .fieldLabel {
          color: #CC0000;
      }
      FORM .formControlError .textInput, FORM .formControlError .selectInput {
          color: #CC0000;
          border: #CC0000 solid 1px;
      }
      FORM .radio_wrap input, FORM .checkbox_wrap input {
          margin-left: 0;
      }
      .spDialogBox .DialogTable {
          height: 100%;
          border: 1px solid #c6c6c6;
          background-color: #EBEBEB;
      }
      .spDialogBox .DialogHeader {
          background-color: #EBEBEB;
      }
      .spDialogBox .DialogBody {
          background-color: #EBEBEB;
      }
      .spDialogBox .DialogTitleDiv {
          margin-left: 5px;
      }
      .spDialogBox .x-panel-inline-icon {
          display: none;
      }
      .spDialogBox .Caption {
          font-family: Verdana;
          font-size: 13px;
          font-weight: bold;
          padding: 0;
      }
      .CalendarWidget {
      }
      .CalendarWidget .navbar {
          width: 100%;
          background: #1B2E73 none;
          vertical-align: middle;
          color: #FFFFFF;
      }
      .CalendarWidget .navbar .header {
          font-family: Verdana, Arial, sans-serif;
          font-size: 11px;
          text-align: center;
          color: #FFFFFF;
          background-color: #1B2E73;
      }
      .CalendarWidget .table {
          font-family: Verdana, Arial, sans-serif;
          font-size: 11px;
          text-align: center;
          border-left: 1px solid #1B2E73;
      }
      .CalendarWidget .weekheader {
          background-color: #ACA899;
          color: #FFFFFF;
      }
      .CalendarWidget .weekheader .days {
          background-color: #88A2CC;
          border-bottom: 1px solid #1B2E73;
          border-right: 1px solid #1B2E73;
          width: 2.5em;
      }
      .CalendarWidget .cell {
          border-bottom: 1px solid #1B2E73;
          border-right: 1px solid #1B2E73;
          cursor: pointer;
      }
      .CalendarWidget .cell-disable {
          border-bottom: 1px solid #1B2E73;
          border-right: 1px solid #1B2E73;
          cursor: default;
          color: #FEFEFE;
      }
      .CalendarWidget .empty {
          border-bottom: 1px solid #1B2E73;
          border-right: 1px solid #1B2E73;
      }
      .CalendarWidget .empty-weekend {
          background-color: #E3EBF5;
          border-bottom: 1px solid #1B2E73;
          border-right: 1px solid #1B2E73;
      }
      .CalendarWidget .cell .gwt-HTML {
          color: #0000FF;
      }
      .CalendarWidget .cell .gwt-HTML span {
          width: 100%;
          height: 100%;
          line-height: 17px;
      }
      .CalendarWidget .cell-disable .gwt-HTML {
          color: #888888;
      }
      .CalendarWidget .cell-disable .gwt-HTML span {
          width: 100%;
          height: 100%;
          line-height: 17px;
      }
      .CalendarWidget .today .gwt-HTML {
          background-color: #EC7411;
          color: #FFFFFF;
      }
      .CalendarWidget .day .gwt-HTML {
          background-color: #FFFFFF;
          color: #0000FF;
      }
      .CalendarWidget .weekend .gwt-HTML {
          background-color: #E3EBF5;
      }
      #submitButton {
          color: #FFFFFF;
          background-color: <?php echo $bcolor ?> ;/* #135984; */
          border: none;
          width: 141px;
          margin-left: 7px;
          margin-top: 4px;
          height: 30px;
          font-size: 16px;
          font-family: Arial;
          font-weight: 700;
          border-radius: 3px;
      }
      .content-table {
        margin-left: auto;
        margin-right: auto;
        }
  </style>

  <?php
  require_once $_SERVER['DOCUMENT_ROOT'] . '/app/Mage.php';

  // gather query parameters
  $method = $_SERVER["REQUEST_METHOD"];
  $first = $_POST['FIRSTNAME'];
  $last = $_POST['LASTNAME'];
  $email = $_POST['Email'];
  define('SYSTEM_ID', 'SHOP');

  // include library
  include($_SERVER['DOCUMENT_ROOT'] . "/CDH.php");
  $cdh = new CDH($_SERVER["ESB_URL"]);

  if ( strcmp($method, 'POST') == 0 ) {
      $magento_id = $cdh->set_user($email, null, $first, $last);

      $sub_array = array(
          $code=>'true',
          'MRKHS'=>$_POST['MARKETINGHOUSE_FLAG-BOX']=='on'?'true':'false',
          'MRK3P'=>$_POST['MARKETINGHOUSE_FLAG-BOX']=='on'?'true':'false' );

      $sub_status = $cdh->set_subscriptions($email, $magento_id, $first, '', $last, $sub_array, $session_id) ;

      $base = Mage::getBaseUrl();
      $url = $base . 'frame-thankyou?first=' . $first . '&last=' . $last . '&bcolor=' . urlencode($bcolor) . '&img=' . $img . '&name=' . urlencode($name) ;
      echo '<META HTTP-EQUIV=REFRESH CONTENT="1; '.$url.'">';
      exit;

  }
  ?>

  <div id="everything" style="display: block;">
      <table border="0" cellspacing="0" cellpadding="0" class="content-table" >
          <tbody>
          <tr>
              <td style="padding: 10px 10px;">
                  <table align="center" width="600" border="0" cellspacing="0" cellpadding="0">
                      <tbody>
                      <tr>
                          <td colspan="2">
                               <?php if ( $img ) echo '<img src="' . $img . '" width="580" alt="">'?>
                          </td>
                      </tr>
                      <tr>
                          <td valign="top" style="padding:12px; font-size:14px; font-family:Arial, Helvetica, sans-serif">
                              <?php if ( $sb_img ) echo '<img name="STW_mobile.jpg" src="' . $sb_img . '" width="210" alt="">' ; ?>
                              <p><?php echo $text ?></p>
                          </td>
                          <td valign="top" style="padding:10px; width:300px;font-family:Arial, Helvetica, sans-serif">
                                <span style="display: inline-block; position: relative;">
                                <form method="post" onsubmit="return PostForm();return false;">
                                    <table cellpadding="0" cellspacing="0" border="0">
                                        <tbody>
                                            <tr>
                                                <td style="padding: 5px 0px 0px 5px;">
                                                <div style="position: relative; overflow: hidden; width:300px;">
                                                <div style="width: 300px; overflow: hidden; ">
                                                <div class="sectionHeader" style="width: 300px; margin: 5px 3px; ">Get <?php echo $name ?>.</div>
                                                </div>
                                                </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="padding: 5px 0px 0px 5px;">
                                                <div style="position: relative; overflow: hidden; width:300px;" id="container_EMAIL">
                                                <div style="width: 294px; overflow: hidden; ">
                                                <div class="fieldLabel" style="width: 294px; margin: 5px 3px; font-family: Arial; font-size: 14px; color: #000000; font-weight: bold; text-decoration: none; font-style: normal; ">My Email Address<span class="required" aria-required="true">*</span></div>
                                                </div>
                                                <input required type="text" name="Email" id="Email" label="My Email Address" class="textInput defaultText" style="margin: 0 3px 5px 3px; height: 20px; width: 294px;">
                                                </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="padding: 5px 0px 0px 5px;">
                                                <div style="position: relative; overflow: hidden; width:300px;" id="container_COLUMN23">
                                                <div style="width: 294px; overflow: hidden; ">
                                                <div class="fieldLabel" style="width: 294px; margin: 5px 3px; font-family: Arial; font-size: 14px; color: #000000; font-weight: bold; text-decoration: none; font-style: normal; ">First Name<span class="required" aria-required="true">*</span></div>
                                                </div>
                                                <input required type="text" name="FIRSTNAME" id="FIRSTNAME" label="First Name" class="textInput defaultText" style="margin: 0 3px 5px 3px; height: 20px; width: 294px;" >
                                                </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="padding: 5px 0px 0px 5px;">
                                                <div style="position: relative; overflow: hidden; width:300px;" id="container_COLUMN6">
                                                <div style="width: 294px; overflow: hidden; ">
                                                <div class="fieldLabel" style="width: 294px; margin: 5px 3px; font-family: Arial; font-size: 14px; color: #000000; font-weight: bold; text-decoration: none; font-style: normal; ">Last Name<span class="required" aria-required="true">*</span></div>
                                                </div>
                                                <input required type="text" name="LASTNAME" id="LASTNAME" label="Last Name" class="textInput defaultText" style="margin: 0 3px 5px 3px; height: 20px; width: 294px;" >
                                                </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="padding: 5px 0px 0px 5px;">
                                                <div style="position: relative; overflow: hidden; width:300px;">
                                                <div style="width: 294px; overflow: hidden; ">
                                                <div class="paragraph" style="width: 294px; margin: 5px 3px; "><hr>
                                                </div>
                                                </div>
                                                </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td style="padding: 5px 0px 0px 5px;">
                                                <div style="position: relative; overflow: hidden; width:300px;" id="container_COLUMN121">
                                                <div style="margin: 0px 0px 0px 3px;">
                                                <table cellspacing="0" cellpadding="0" border="0">
                                                    <tbody>
                                                        <tr style="height: 20px">
                                                            <td class="fieldLabel" style="font-family: Arial; font-size: 12px; color: #000000; font-weight: bold; text-decoration: none; font-style: normal; "><label class="yesNoCheckboxLabel">
                                                            <input type="checkbox" class="SUBCheckBox" name="MARKETINGHOUSE_FLAG-BOX" id="MARKETINGHOUSE_FLAG-BOX" label="Yes, send me occasional notices about noteworthy products and exclusive offers." checked="">Yes, send me occasional notices about noteworthy products and exclusive offers.</label>
                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                                </div>
                                                </div>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td id="errorMessageContainerId" class="formErrorMessages" style="display: none;"></td>
                                            </tr>
                                            <tr>
                                                <td style="padding: 5px 0px 0px 5px;">
                                                <div style="position: relative; overflow: hidden; width:300px;">
                                                <table cellspacing="0" cellpadding="0" border="0">
                                                    <tbody>
                                                        <tr>
                                                            <td style="padding-right: 10px;">
                                                            <input id="submitButton" type="submit" class="defaultText buttonStyle" value="Subscribe Now">
                                                            </td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                                </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </form>
                                </span>
                          </td>
                      </tr>
                      </tbody>
                  </table>
              </td>
          </tr>
          </tbody>
      </table>
  </div>

