  <meta name="viewport" content="width=device-width, initial-scale=1">

  <?php
  require_once $_SERVER['DOCUMENT_ROOT'] . '/app/Mage.php';

  // gather query parameters
  $method = $_SERVER["REQUEST_METHOD"];

  // iframe query params
  $name = $_GET['name'];
  $first = $_GET['first'];
  $last = $_GET['last'];
  $bcolor = $_GET['bcolor'];
  $img = $_GET['img'];  
  ?>

  <style type="text/css">
      FORM {
          background-color: transparent;
      }
      FORM .fieldLabel {
          font-family: Arial; font-size: 11px; color: #000000; font-weight: bold; text-decoration: none; font-style: normal;
      }
      FORM .yesNoCheckboxLabel {
          display: block;
          padding-left: 20px;
          text-indent: -20px;
      }
      FORM .fieldLabel .required {
          color: #CC0000 !important;
      }
      FORM .sectionHeader {
          font-family: Arial; font-size: 16px; color: #000000; font-weight: bold; text-decoration: none; font-style: normal;
      }
      FORM .paragraph {
          font-family: Arial; font-size: 10px; color: #000000; font-weight: normal; text-decoration: none; font-style: normal;
      }
      FORM TD, FORM .defaultText {
          font-family: Arial, Helvetica, sans-serif;
          font-size: 11px;
          color: black;
      }
      /**
      HACK FOR IE: IE always adds extra space to make an input huge and weird. this will
      force it to truncate our label and not keep the extra spaces.
      **/
      * HTML .buttonStyle {
          width: 1px;
          overflow:visible;
          padding-left: 5px;
          padding-right: 5px;
      }
      FORM .textInput {
          border: 1px solid #B5B8C8;
          padding:1px 3px;
      }
      FORM .selectInput {
          border: 1px solid #B5B8C8;
      }
      FORM .formErrorMessages DIV {
          font-family: Arial; font-size: 11px; color: #CC0000; font-weight: normal; text-decoration: none; font-style: normal;
          margin: 0 0 2px 7px;
      }
      FORM .formControlError .fieldLabel {
          color: #CC0000;
      }
      FORM .formControlError .textInput, FORM .formControlError .selectInput {
          color: #CC0000;
          border: #CC0000 solid 1px;
      }
      FORM .radio_wrap input, FORM .checkbox_wrap input {
          margin-left: 0;
      }
      .spDialogBox .DialogTable {
          height: 100%;
          border: 1px solid #c6c6c6;
          background-color: #EBEBEB;
      }
      .spDialogBox .DialogHeader {
          background-color: #EBEBEB;
      }
      .spDialogBox .DialogBody {
          background-color: #EBEBEB;
      }
      .spDialogBox .DialogTitleDiv {
          margin-left: 5px;
      }
      .spDialogBox .x-panel-inline-icon {
          display: none;
      }
      .spDialogBox .Caption {
          font-family: Verdana;
          font-size: 13px;
          font-weight: bold;
          padding: 0;
      }
      .CalendarWidget {
      }
      .CalendarWidget .navbar {
          width: 100%;
          background: #1B2E73 none;
          vertical-align: middle;
          color: #FFFFFF;
      }
      .CalendarWidget .navbar .header {
          font-family: Verdana, Arial, sans-serif;
          font-size: 11px;
          text-align: center;
          color: #FFFFFF;
          background-color: #1B2E73;
      }
      .CalendarWidget .table {
          font-family: Verdana, Arial, sans-serif;
          font-size: 11px;
          text-align: center;
          border-left: 1px solid #1B2E73;
      }
      .CalendarWidget .weekheader {
          background-color: #ACA899;
          color: #FFFFFF;
      }
      .CalendarWidget .weekheader .days {
          background-color: #88A2CC;
          border-bottom: 1px solid #1B2E73;
          border-right: 1px solid #1B2E73;
          width: 2.5em;
      }
      .CalendarWidget .cell {
          border-bottom: 1px solid #1B2E73;
          border-right: 1px solid #1B2E73;
          cursor: pointer;
      }
      .CalendarWidget .cell-disable {
          border-bottom: 1px solid #1B2E73;
          border-right: 1px solid #1B2E73;
          cursor: default;
          color: #FEFEFE;
      }
      .CalendarWidget .empty {
          border-bottom: 1px solid #1B2E73;
          border-right: 1px solid #1B2E73;
      }
      .CalendarWidget .empty-weekend {
          background-color: #E3EBF5;
          border-bottom: 1px solid #1B2E73;
          border-right: 1px solid #1B2E73;
      }
      .CalendarWidget .cell .gwt-HTML {
          color: #0000FF;
      }
      .CalendarWidget .cell .gwt-HTML span {
          width: 100%;
          height: 100%;
          line-height: 17px;
      }
      .CalendarWidget .cell-disable .gwt-HTML {
          color: #888888;
      }
      .CalendarWidget .cell-disable .gwt-HTML span {
          width: 100%;
          height: 100%;
          line-height: 17px;
      }
      .CalendarWidget .today .gwt-HTML {
          background-color: #EC7411;
          color: #FFFFFF;
      }
      .CalendarWidget .day .gwt-HTML {
          background-color: #FFFFFF;
          color: #0000FF;
      }
      .CalendarWidget .weekend .gwt-HTML {
          background-color: #E3EBF5;
      }
      #submitButton {
          color: #FFFFFF;
          background-color: <?php echo $bcolor ?> ;/* #135984; */
          border: none;
          width: 141px;
          margin-left: 7px;
          margin-top: 4px;
          height: 30px;
          font-size: 16px;
          font-family: Arial;
          font-weight: 700;
          border-radius: 3px;
      }

  </style>
  <link rel="stylesheet" type="text/css" href="/skin/frontend/rwd/eclipse/images/landing-pages/preferences/css/grid.css">
  <div class="w-section email-pref-header">
    <img src="<?php echo $img?>" width="200" alt="">
 
    <br/><br/>Thank you <?php echo $first ?> <?php echo $last ?> for your subscription to <?php echo $name ?>.  Your e-letter will begin on the next scheduled send.
     
    <br/><br/>Kindly add “messages.bottomlineinc.com” to your Safe Senders list to ensure delivery to your Inbox.
     
    <br/><br/>Thank you
    <br/>Customer Service
    <br/><br/><br/>
  </div>

