<?php $oGiftCardSession = Mage::getSingleton('giftcards/session'); ?>

<div class="discount">
    <div class="sp-methods">
        <form method="post" action="<?php echo $this->getUrl('giftcards/cart/giftcardActive'); ?>" id="giftcardAgree">
            <div class="input-box">
                <input type="checkbox" value="1" name="giftcard_use" id="giftcard_use" class="checkbox" onclick="agreeMethod.save();" <?php echo $oGiftCardSession->getActive() ? 'checked="checked"' : '' ?>>
                <label for="giftcard_use"><?php echo $this->__('Gift Cards'); ?></label>
            </div>
        </form>
    </div>
    <?php if($oGiftCardSession->getActive()): ?>
    <div class="discount-form giftcard-payment-method">
        <form method="post" action="<?php echo $this->getUrl('giftcards/cart/activateGiftCard'); ?>" id="activateGiftCard">
            <div class="col2-set giftcards">
                <div class="col-1">
                    <label for="giftcard_code"><?php echo $this->__('Enter your Gift Card'); ?></label>
                    <div class="input-box">
                        <input value="" name="giftcard_code" id="giftcard_code" class="input-text">
                    </div>
                </div>
<?php if(Mage::getStoreConfigFlag('giftcards/default/split_amount')):?>
                 <div class="col-2">
                    <label for="giftcard_code"><?php echo $this->__('Amount'); ?></label>
                    <div class="input-box">
                        <input value="" name="giftcard_amount" id="giftcard_amount" class="input-text">
                    </div>
                </div>
<?php endif;?>
            </div>
            <br/>
            <div class="buttons-set">
                <button value="<?php echo $this->__('Activate') ?>" onclick="activateGiftCard.save()" class="button"
                    title="Activate" type="button"><span><span><?php echo $this->__('Activate') ?></span></span>
                </button>
            </div>
        </form>

        <?php $currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); $temp = 0; ?>
        <?php if($oGiftCardSession->getActive()) {
            foreach($oGiftCardSession->getFrontOptions() as $k => $v)
            {
                if($temp) {
                    echo '<br/><br/>';
                }
                echo '<b>'.$currencySymbol.$v['applied'].' '.$this->__('applied from Gift Card').' '.$v['code'].'.</b><br/>';
                echo $this->__('Remaining card balance').': '.$currencySymbol.$v['remaining'].'. (<a href="#" onclick="deActivateGiftCard.deactivate('.$k.');">'.$this->__('Remove').'</a>)';
                $temp = 1;
            }
        }
        ?>
    </div>

    <?php endif;?>

</div>
