<?php
/* Webtex Gift Cards
 *
 * Items.phtml
 * (c) WebtexSoftware 2015
 */

$_helper = Mage::helper("giftcards");
$_items  = $this->getUsedGiftCards();
$oGiftCardSession = Mage::getSingleton('giftcards/session');

?>

<?php $currencySymbol = Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); $temp = 0; ?>
<?php if($oGiftCardSession->getActive()):?>
<br />
<table class="data-table giftcards-discount-table">
    <th class="a-center"><?php echo $this->__("Card")?></th>
    <th class="a-center"><?php echo $this->__("Balance")?></th>
    <th class="a-center"><?php echo $this->__("Amount to use")?></th>
    <th class="a-center"></th>
    <th class="a-center"></th>
    <tbody>
<?php foreach($_items as $_item):?>
<tr>
    <td class="a-center giftcards-td"><?php echo $_item['giftcard_code'] ?></td>
    <td class="a-right giftcards-td"><?php echo Mage::helper('core')->formatPrice($_item['balance'], false) ?></td>
    <td class="a-center giftcards-td"><input type="text" class="input-text giftcard-amount" id="amount_<?php echo $_item['giftcard_id']?>" name="amount[<?php echo $_item['giftcard_id']?>]" value="" /></td>
    <td class="a-center giftcards-td apply-button"><button type="button" class="button giftcards-button-apply" onclick="applyGiftcardAmount(<?php echo $_item['giftcard_id']?>); return false;"><span><?php echo $this->__("Apply");?></span></button></td>
    <td class="a-center giftcards-td remove-button"><button type="button" class="button giftcards-button-remove" onclick="removeGiftcard(<?php echo $_item['giftcard_id']?>); return false;"><span><?php echo $this->__("X");?></span></button></td>
</tr>
<?php endforeach; ?>
    </tbody>
</table>

<?php endif; ?>

<script type="text/javascript">

    function applyGiftcardAmount(itemId){
        var giftcard = itemId;
        var amount = $("amount_"+itemId).value;

        var request = new Ajax.Request(
            '<?php echo $this::getUrl('giftcards/cart/applyamount') ?>',
                {
                  method: "post",
                  onSuccess: function(transport){
                      response = eval('('+transport.responseText+')'); 
                      if(transport.status == 200) {
                          if(response.success){
                              $('giftcard-section').update(response.update);
                              $$('.giftcards-apply-table')[0].update(response.table);
                          }
                          alert(response.message);
                      }
                    },
                  parameters: {id: itemId, amount: amount}
                }
            );
    }

    function removeGiftcard(itemId){
        var request = new Ajax.Request(
        '<?php echo $this::getUrl('giftcards/cart/removegiftcard') ?>',
        {
          method: "post",
          parameters: {id: itemId},
          onSuccess: function(transport){
                  response = eval('('+transport.responseText+')'); 
                  if(transport.status == 200) {
                      if(response.success){
                          $('giftcard-section').update(response.update);
                          $$('.giftcards-apply-table')[0].update(response.table);
                      }
                      alert(response.message);
                  }
          }
        });
    }

</script>
        
